"""Natural-language regression task suite for v11 behavior checks."""

from __future__ import annotations


V11_TASK_SUITE = [
    {
        "case_id": "ambiguous_meson_operator",
        "category": "ambiguous_meson",
        "request": "I want a meson correlator script but I am not sure about the exact operator",
        "expected_product_status": "needs_input",
        "expected_physics_target": "meson_two_point_correlator_unspecified",
        "expected_workflow_target": None,
        "expected_clarification_mode": "physics_confirmation",
        "expected_primary_action_kind": "continue_by_reply",
        "expected_nearest_fix_kind": None,
        "expected_formula_preview": True,
        "expected_workflow_preview": True,
        "expected_candidate_prefix": [
            "meson_two_point_correlator_unspecified",
            "pion_two_point_correlator",
            "meson_spectrum_correlator",
        ],
        "expected_formula_prefix": [
            "meson_operator_needs_channel_choice",
            "pion_pseudoscalar_gamma5_twopt",
        ],
    },
    {
        "case_id": "explicit_pion_2pt",
        "category": "explicit_supported",
        "request": "please compute the pion two-point correlator",
        "expected_product_status": "needs_input",
        "expected_physics_target": "pion_two_point_correlator",
        "expected_workflow_target": "pion_2pt_chroma_wall_local_zero_momentum_npy_v1",
        "expected_clarification_mode": "task_fields",
        "expected_primary_action_kind": "continue_by_set",
        "expected_nearest_fix_kind": None,
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "explicit_pion_pcac",
        "category": "explicit_supported",
        "request": "please compute pion pcac ratio",
        "expected_product_status": "needs_input",
        "expected_physics_target": "pion_pcac_ratio_correlator",
        "expected_workflow_target": "pion_pcac_chroma_wall_local_zero_momentum_npy_v1",
        "expected_clarification_mode": "task_fields",
        "expected_primary_action_kind": "continue_by_set",
        "expected_nearest_fix_kind": None,
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "explicit_meson_spec",
        "category": "explicit_supported",
        "request": "please compute meson spectroscopy correlators",
        "expected_product_status": "needs_input",
        "expected_physics_target": "meson_spectrum_correlator",
        "expected_workflow_target": "meson_spec_chroma_wall_gamma5_axial_mom2max9_npy_v1",
        "expected_clarification_mode": "task_fields",
        "expected_primary_action_kind": "continue_by_set",
        "expected_nearest_fix_kind": None,
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "explicit_rho",
        "category": "explicit_supported",
        "request": "please compute the rho meson two-point correlator",
        "expected_product_status": "needs_input",
        "expected_physics_target": "rho_vector_meson_correlator",
        "expected_workflow_target": "rho_vector_chroma_wall_local_zero_momentum_npy_v1",
        "expected_clarification_mode": "task_fields",
        "expected_primary_action_kind": "continue_by_set",
        "expected_nearest_fix_kind": None,
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "explicit_proton",
        "category": "explicit_supported",
        "request": "please compute the proton two-point correlator",
        "expected_product_status": "needs_input",
        "expected_physics_target": "proton_two_point_correlator",
        "expected_workflow_target": "proton_2pt_chroma_wall_local_zero_momentum_npy_v1",
        "expected_clarification_mode": "task_fields",
        "expected_primary_action_kind": "continue_by_set",
        "expected_nearest_fix_kind": None,
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "explicit_quark_propagator",
        "category": "propagator",
        "request": "please generate a quark propagator",
        "expected_product_status": "needs_input",
        "expected_physics_target": "quark_propagator",
        "expected_workflow_target": "quark_propagator_chroma_point_hdf5_v1",
        "expected_clarification_mode": "task_fields",
        "expected_primary_action_kind": "continue_by_set",
        "expected_nearest_fix_kind": None,
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "explicit_gaussian_shell_propagator",
        "category": "propagator",
        "request": "please generate a gaussian-shell quark propagator",
        "expected_product_status": "needs_input",
        "expected_physics_target": "quark_propagator",
        "expected_workflow_target": "quark_propagator_gaussian_shell_chroma_hdf5_v1",
        "expected_clarification_mode": "task_fields",
        "expected_primary_action_kind": "continue_by_set",
        "expected_nearest_fix_kind": None,
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "rough_gauge_smear_family",
        "category": "smear",
        "request": "please smear this gauge field and save the result",
        "expected_product_status": "needs_input",
        "expected_physics_target": "stout_smeared_gauge_configuration",
        "expected_workflow_target": None,
        "expected_clarification_mode": "physics_confirmation",
        "expected_primary_action_kind": "continue_by_reply",
        "expected_nearest_fix_kind": None,
        "expected_formula_preview": True,
        "expected_workflow_preview": True,
        "expected_candidate_prefix": [
            "stout_smeared_gauge_configuration",
            "ape_smeared_gauge_configuration",
            "hyp_smeared_gauge_configuration",
        ],
        "expected_formula_prefix": [
            "stout_smear_one_step_rho0241_dirignore3",
            "ape_smear_one_step_alpha25_dirignore4",
        ],
    },
    {
        "case_id": "explicit_wilson_flow",
        "category": "flow",
        "request": "please run wilson flow on this gauge configuration",
        "expected_product_status": "needs_input",
        "expected_physics_target": "wilson_flow_energy_observable",
        "expected_workflow_target": "wilson_flow_chroma_qio_energy_npy_v1",
        "expected_clarification_mode": "task_fields",
        "expected_primary_action_kind": "continue_by_set",
        "expected_nearest_fix_kind": None,
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "unsupported_neutron",
        "category": "unsupported_baryon",
        "request": "please compute the neutron two-point correlator",
        "expected_product_status": "unsupported",
        "expected_physics_target": "neutron_two_point_correlator",
        "expected_workflow_target": None,
        "expected_clarification_mode": "not_applicable",
        "expected_primary_action_kind": "retry_supported_workflow",
        "expected_nearest_fix_kind": "retry_supported_workflow",
        "expected_unsupported_scope": "physics",
        "expected_shortest_fix_target": "proton_2pt_chroma_wall_local_zero_momentum_npy_v1",
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "unsupported_quark_wall_source",
        "category": "unsupported_propagator_variant",
        "request": (
            "please generate a quark propagator from gauge /tmp/cfg_0001.lime wall source "
            "lattice size 24 24 24 72 grid 1 1 1 2 mass=-0.2770 xi_0=1.0 nu=1.0 "
            "coeff_t=1.160920226 coeff_r=1.160920226 tol=1e-12 maxiter=1000 "
            "source timeslice 0 outputs/pt_prop.h5 outputs/run_quark.py "
            "resource_path=.cache/quda cluster_launch=local"
        ),
        "expected_product_status": "unsupported",
        "expected_physics_target": "quark_propagator",
        "expected_workflow_target": None,
        "expected_clarification_mode": "not_applicable",
        "expected_primary_action_kind": "retry_supported_workflow",
        "expected_nearest_fix_kind": "retry_supported_workflow",
        "expected_unsupported_scope": "physics",
        "expected_shortest_fix_target": "quark_propagator_chroma_point_hdf5_v1",
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "unsupported_stout_existing_propagator",
        "category": "unsupported_smear_variant",
        "request": (
            "please generate a stout-smeared gauge from existing propagator /tmp/q.npy "
            "lattice size 24 24 24 72 grid 1 1 1 2 outputs/s.npy outputs/s.py "
            "resource_path=.cache/quda cluster_launch=local"
        ),
        "expected_product_status": "unsupported",
        "expected_physics_target": "stout_smeared_gauge_configuration",
        "expected_workflow_target": None,
        "expected_clarification_mode": "not_applicable",
        "expected_primary_action_kind": "retry_supported_workflow",
        "expected_nearest_fix_kind": "retry_supported_workflow",
        "expected_unsupported_scope": "implementation",
        "expected_shortest_fix_target": "stout_smear_chroma_qio_npy_v1",
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "unsupported_wilson_flow_existing_propagator",
        "category": "unsupported_flow_variant",
        "request": (
            "please run wilson flow from existing propagator /tmp/q.npy lattice size 24 24 24 72 "
            "grid 1 1 1 2 flow_steps=100 flow_epsilon=1.0 outputs/f.npy outputs/f.py "
            "resource_path=.cache/quda cluster_launch=local"
        ),
        "expected_product_status": "unsupported",
        "expected_physics_target": "wilson_flow_energy_observable",
        "expected_workflow_target": None,
        "expected_clarification_mode": "not_applicable",
        "expected_primary_action_kind": "retry_supported_workflow",
        "expected_nearest_fix_kind": "retry_supported_workflow",
        "expected_unsupported_scope": "implementation",
        "expected_shortest_fix_target": "wilson_flow_chroma_qio_energy_npy_v1",
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
    {
        "case_id": "unsupported_eta_needs_clarification",
        "category": "non_grounded_meson_like",
        "request": "please compute the eta meson correlator",
        "expected_product_status": "needs_input",
        "expected_physics_target": "meson_two_point_correlator_unspecified",
        "expected_workflow_target": None,
        "expected_clarification_mode": "physics_confirmation",
        "expected_primary_action_kind": "continue_by_reply",
        "expected_nearest_fix_kind": None,
        "expected_formula_preview": True,
        "expected_workflow_preview": True,
        "expected_candidate_prefix": [
            "meson_two_point_correlator_unspecified",
            "pion_two_point_correlator",
            "meson_spectrum_correlator",
        ],
        "expected_formula_prefix": [
            "meson_operator_needs_channel_choice",
            "pion_pseudoscalar_gamma5_twopt",
        ],
    },
    {
        "case_id": "unsupported_meson_spec_gauge_fixed",
        "category": "non_grounded_meson_like",
        "request": "please compute the meson spectrum correlator with gauge fixed",
        "expected_product_status": "unsupported",
        "expected_physics_target": "meson_spectrum_correlator",
        "expected_workflow_target": None,
        "expected_clarification_mode": "not_applicable",
        "expected_primary_action_kind": "retry_supported_workflow",
        "expected_nearest_fix_kind": "retry_supported_workflow",
        "expected_unsupported_scope": "physics",
        "expected_shortest_fix_target": "meson_spec_chroma_wall_gamma5_axial_mom2max9_npy_v1",
        "expected_formula_preview": False,
        "expected_workflow_preview": True,
    },
]
