#!/usr/bin/env python3
"""Render a concise architecture summary from a generated PyQUDA index."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_INDEX = REPO_ROOT / "data" / "pyquda_index.json"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "PYQUDA_ARCHITECTURE.md"


AREA_TITLES = {
    "pyquda_core": "Core bindings and runtime",
    "pyquda_utils": "High-level utilities",
    "pyquda_io": "Format I/O layer",
    "pyquda_plugins": "Plugin builder",
    "tests": "Validation surface",
    "examples": "Example workflows",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render a Markdown architecture summary from a JSON index.")
    parser.add_argument("--index", type=Path, default=DEFAULT_INDEX, help="Path to a JSON index generated by index_pyquda_repo.py.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Where to write the Markdown summary.")
    return parser.parse_args()


def load_index(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(
            f"Index file not found: {path}. Run scripts/index_pyquda_repo.py first or pass --index."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def find_module(index: dict, module_name: str) -> dict | None:
    for module in index["python_modules"]:
        if module["module_name"] == module_name:
            return module
    return None


def format_area_section(index: dict, area_name: str) -> list[str]:
    files = [item for item in index["files"] if item["area"] == area_name]
    if not files:
        return []
    python_modules = [item for item in index["python_modules"] if item["area"] == area_name]
    category_counts: dict[str, int] = {}
    for item in files:
        category_counts[item["category"]] = category_counts.get(item["category"], 0) + 1
    lines = [f"## {AREA_TITLES.get(area_name, area_name)}", ""]
    lines.append(f"- Scope: `{area_name}` with {len(files)} indexed files.")
    dominant = ", ".join(f"`{key}`={value}" for key, value in sorted(category_counts.items()))
    lines.append(f"- File mix: {dominant}.")
    if python_modules:
        sample = ", ".join(f"`{item['module_name']}`" for item in python_modules[:5] if item["module_name"])
        if sample:
            lines.append(f"- Representative modules: {sample}.")
    outgoing = index["dependency_edges"].get(area_name, {})
    if outgoing:
        deps = ", ".join(f"`{target}` ({count})" for target, count in sorted(outgoing.items()))
        lines.append(f"- Internal dependencies observed from Python imports: {deps}.")
    lines.append("")
    return lines


def render_markdown(index: dict) -> str:
    summary = index["summary"]
    lines = [
        "# PyQUDA Architecture Summary",
        "",
        "This document is generated from `data/pyquda_index.json` by `scripts/render_pyquda_architecture.py`.",
        "",
        "## Repository shape",
        "",
        f"- Indexed scopes: {', '.join(f'`{scope['name']}`' for scope in index['scopes'] if scope['exists'])}.",
        f"- Indexed files: {summary['file_count']} total, with {summary['python_module_count']} Python files and {summary['cython_file_count']} Cython sources.",
        f"- Top-level packaging files: {', '.join(f'`{name}`' for name in index['top_level_files'])}.",
        "",
        "## Layered architecture",
        "",
        "- `pyquda_core` owns the `pyquda` runtime package and `pyquda_comm`, which initialize MPI/device state and expose QUDA-backed field, Dirac, action, and HMC APIs.",
        "- `pyquda_utils` is a pure-Python layer that imports `pyquda` and `pyquda_comm` to provide source construction, phases, FFT, eigensolvers, HMC parameters, and convenience wrappers.",
        "- `pyquda_io` is a format-oriented layer that re-exports readers and writers for Chroma, MILC, KYU, XQCD, NERSC, OpenQCD, NPY, and LIME-based workflows.",
        "- `pyquda_plugins` builds optional compiled extensions against external libraries and ships plugin-facing packages such as `pycontract` and `pygwu`.",
        "- `tests` and `examples` sit on top of those layers and act as the main executable surface for users and regression coverage.",
        "",
    ]

    pyquda_init = find_module(index, "pyquda")
    pyquda_io_init = find_module(index, "pyquda_io")
    plugin_main = find_module(index, "pyquda_plugins.__main__")
    if pyquda_init or pyquda_io_init or plugin_main:
        lines.extend(
            [
                "## Notable entry points",
                "",
            ]
        )
        if pyquda_init:
            lines.append(
                f"- `pyquda` entry point: `{pyquda_init['path']}` exports initialization helpers and is the runtime front door for QUDA setup."
            )
        if pyquda_io_init:
            lines.append(
                f"- `pyquda_io` entry point: `{pyquda_io_init['path']}` re-exports file-format readers and writers from format-specific modules."
            )
        if plugin_main:
            lines.append(
                f"- `pyquda_plugins` CLI: `{plugin_main['path']}` builds and installs plugin extensions by driving Cython and setuptools."
            )
        lines.append("")

    for area_name in ("pyquda_core", "pyquda_utils", "pyquda_io", "pyquda_plugins", "tests", "examples"):
        lines.extend(format_area_section(index, area_name))

    lines.extend(
        [
            "## Analysis notes",
            "",
            "- Vendored or embedded directories such as `pycparser` and `quda` are excluded from the generated index to keep dependency signals focused on project-owned code.",
            "- The root `pyproject.toml` packages `pyquda_utils`, `pyquda_io`, and `pyquda_plugins`, while `pyquda_core/pyproject.toml` separately packages the `pyquda` runtime and `pyquda_comm` bindings.",
            "- There is no in-repo `docs/` directory upstream; examples and tests currently serve as the clearest executable documentation surface.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    index = load_index(args.index.expanduser().resolve())
    output = args.output.expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_markdown(index), encoding="utf-8")
    print(f"Wrote architecture summary to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
