#!/usr/bin/env python3
"""Generated by pyquda-agent for a pion two-point workflow."""

from __future__ import annotations

from pathlib import Path
import json


TASK_CONFIG = {'gauge_fixed': True,
 'has_existing_propagators': False,
 'momenta': [[0, 0, 0]],
 'momentum_mode': 'projected',
 'notes': 'generate pion 2pt template from gauge with wall source local sink '
          'zero momentum timeslice 0 gauge fixed',
 'output_path': '/Users/zhaodianjun/pyquda-agent/outputs/pion_2pt_generated.py',
 'propagator_paths': [],
 'script_style': 'template',
 'sink_type': 'local',
 'source_timeslices': [0],
 'source_type': 'wall',
 'task_type': 'pion_2pt'}


def load_inputs() -> dict:
    """Resolve input paths and leave physics-specific loading explicit."""
    return {
        "propagator_paths": [Path(path) for path in TASK_CONFIG["propagator_paths"]],
        "source_timeslices": TASK_CONFIG["source_timeslices"],
        "momenta": TASK_CONFIG["momenta"] or [[0, 0, 0]],
    }


def main() -> None:
    inputs = load_inputs()
    print("pion_2pt task configuration:")
    print(json.dumps(TASK_CONFIG, indent=2, sort_keys=True))
    print("Reference files consulted while generating this template:")
    print("- /Users/zhaodianjun/PyQUDA/examples/3_Pion_Proton_2pt.py")
    print("- /Users/zhaodianjun/PyQUDA/tests/test_mesonspec.py")
    print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/core.py")
    print("- /Users/zhaodianjun/pyquda-agent/AGENTS.md")

    if TASK_CONFIG["script_style"] == "complete" and not TASK_CONFIG["has_existing_propagators"]:
        raise RuntimeError(
            "Complete inversion-from-gauge generation still needs gauge path, lattice size, and solver parameters. "
            "Use template mode or extend the task fields first."
        )

    if TASK_CONFIG["has_existing_propagators"]:
        print("TODO: replace this section with project-specific propagator loading and contraction code.")
        print(f"Configured propagator files: {[str(path) for path in inputs['propagator_paths']]}")
    else:
        print("TODO: fill in gauge path, lattice geometry, and Dirac parameters before running inversions.")
        print("Suggested upstream references:")
        print("- ~/PyQUDA/examples/3_Pion_Proton_2pt.py")
        print("- ~/PyQUDA/tests/test_mesonspec.py")

    print(f"Source type: {TASK_CONFIG['source_type']}")
    print(f"Sink type: {TASK_CONFIG['sink_type']}")
    print(f"Momentum mode: {TASK_CONFIG['momentum_mode']}")
    print(f"Gauge fixed: {TASK_CONFIG['gauge_fixed']}")


if __name__ == "__main__":
    main()
