#!/usr/bin/env python3
"""Complete runnable proton two-point workflow generated by pyquda-agent."""

from __future__ import annotations

from itertools import permutations
from pathlib import Path
from time import perf_counter

# Fixed workflow: gauge -> stout smear -> getDirac(multigrid) -> wall source -> parity-projected proton contraction -> npy.
# Review the sibling .physics.json, .task.json, and .plan.json artifacts before treating this script as complete.
# HPC handoff contract:
# - launch mode assumption: local
# - gauge input is expected on a filesystem visible to all ranks
# - only rank 0 writes the final correlator artifact
# - this script assumes the target environment already provides PyQUDA, QUDA, CuPy, opt_einsum, and MPI layout support

WORKFLOW_ID = 'proton_2pt_chroma_wall_local_zero_momentum_npy_v1'
SCRIPT_PATH = Path(__file__).resolve()
TASK_ARTIFACT = SCRIPT_PATH.with_suffix(".task.json")
PHYSICS_ARTIFACT = SCRIPT_PATH.with_suffix(".physics.json")
PLAN_ARTIFACT = SCRIPT_PATH.with_suffix(".plan.json")
GAUGE_PATH = Path('/Users/zhaodianjun/PyQUDA/tests/weak_field.lime')
CORRELATOR_OUTPUT = Path('/Users/zhaodianjun/pyquda-agent/outputs/proton_api.npy')
RESOURCE_PATH = '.cache/quda'
GRID_SIZE = [1, 1, 1, 1]
LATTICE_SIZE = [4, 4, 4, 8]
SOURCE_TIMESLICES = [0]
MASS = 0.09253
XI_0 = 1.0
NU = 1.0
COEFF_T = 1.160920226
COEFF_R = 1.160920226
SOLVER_TOL = 1e-12
SOLVER_MAXITER = 1000
MULTIGRID_BLOCKS = [[6, 6, 6, 4], [4, 4, 4, 9]]
STOUT_SMEAR_STEPS = 1
STOUT_SMEAR_RHO = 0.125
STOUT_SMEAR_NDIM = 4


def _validate_handoff_contract() -> None:
    expected_suffixes = {".lime", ".xml"}
    if GAUGE_PATH.suffix not in expected_suffixes:
        raise ValueError(
            f"Expected a Chroma/QIO gauge path ending in one of {sorted(expected_suffixes)}; got {GAUGE_PATH}"
        )
    if CORRELATOR_OUTPUT.suffix != ".npy":
        raise ValueError(f"Expected a .npy correlator output path; got {CORRELATOR_OUTPUT}")
    if len(LATTICE_SIZE) != 4 or len(GRID_SIZE) != 4:
        raise ValueError("LATTICE_SIZE and GRID_SIZE must both contain exactly four integers.")
    if any(value <= 0 for value in LATTICE_SIZE):
        raise ValueError(f"LATTICE_SIZE must be strictly positive; got {LATTICE_SIZE}")
    if any(value <= 0 for value in GRID_SIZE):
        raise ValueError(f"GRID_SIZE must be strictly positive; got {GRID_SIZE}")
    for axis, (latt_extent, grid_extent) in enumerate(zip(LATTICE_SIZE, GRID_SIZE, strict=True)):
        if latt_extent % grid_extent != 0:
            raise ValueError(
                f"LATTICE_SIZE[{axis}]={latt_extent} must be divisible by GRID_SIZE[{axis}]={grid_extent}"
            )
    if not SOURCE_TIMESLICES:
        raise ValueError("At least one source timeslice is required.")
    global_lt = LATTICE_SIZE[3]
    if global_lt % 2 != 0:
        raise ValueError(f"Current proton workflow requires an even global Lt for the parity-projector construction; got {global_lt}")
    invalid_timeslices = [t_src for t_src in SOURCE_TIMESLICES if t_src < 0 or t_src >= global_lt]
    if invalid_timeslices:
        raise ValueError(
            f"All source timeslices must satisfy 0 <= t_src < {global_lt}; got {invalid_timeslices}"
        )
    if not RESOURCE_PATH:
        raise ValueError("RESOURCE_PATH must be a non-empty string.")
    if not MULTIGRID_BLOCKS:
        raise ValueError("MULTIGRID_BLOCKS must be a non-empty nested list.")
    if STOUT_SMEAR_STEPS is None or STOUT_SMEAR_RHO is None or STOUT_SMEAR_NDIM is None:
        raise ValueError("Stout-smear parameters must all be resolved before execution.")
    if not TASK_ARTIFACT.exists() or not PHYSICS_ARTIFACT.exists() or not PLAN_ARTIFACT.exists():
        raise FileNotFoundError(
            "Expected sibling review artifacts next to this script: "
            f"{PHYSICS_ARTIFACT.name}, {TASK_ARTIFACT.name}, and {PLAN_ARTIFACT.name}"
        )


def _print_handoff_summary() -> None:
    print(f"Workflow ID: {WORKFLOW_ID}")
    print(f"Launch assumption: local")
    print(f"Gauge input path: {GAUGE_PATH}")
    print(f"Correlator output path: {CORRELATOR_OUTPUT}")
    print(f"Physics artifact: {PHYSICS_ARTIFACT}")
    print(f"Structured task artifact: {TASK_ARTIFACT}")
    print(f"Implementation plan artifact: {PLAN_ARTIFACT}")
    print(f"Multigrid blocks: {MULTIGRID_BLOCKS}")
    print(f"Stout smear: steps={STOUT_SMEAR_STEPS}, rho={STOUT_SMEAR_RHO}, ndim={STOUT_SMEAR_NDIM}")
    print("Filesystem contract: gauge input must be visible to all ranks; only rank 0 writes output.")
    print("Layout contract: lattice extents must be divisible by the requested QUDA/MPI grid.")


def _load_runtime_modules():
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'numpy'. Activate a PyQUDA Python environment with NumPy installed before running this script."
        ) from exc

    try:
        import cupy as cp
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'cupy'. Activate a PyQUDA environment with CuPy installed before running this script."
        ) from exc

    try:
        from opt_einsum import contract
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'opt_einsum'. Activate a PyQUDA environment with opt_einsum installed before running this script."
        ) from exc

    try:
        from pyquda_utils import core, gamma, io
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda_utils'. If you are running from a local PyQUDA checkout, build/install PyQUDA first "
            "or export PYTHONPATH=~/PyQUDA after following the upstream development instructions."
        ) from exc

    try:
        import pyquda  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda'. The PyQUDA core bindings are not available in this Python environment."
        ) from exc

    return np, cp, contract, core, gamma, io


def contract_proton_zero_momentum(propagator, latt_info, t_src, global_lt):
    _, cp, contract, _, gamma, _ = _load_runtime_modules()
    c_matrix = gamma.gamma(2) @ gamma.gamma(8)
    gamma0 = gamma.gamma(0)
    gamma4 = gamma.gamma(8)
    gamma5 = gamma.gamma(15)
    half_t = global_lt // 2
    parity_projector = cp.zeros((global_lt, 4, 4), "<c16")
    parity_projector[:half_t] = (gamma0 + gamma4) / 2
    parity_projector[half_t:] = (gamma0 - gamma4) / 2
    temporal_sign = cp.ones((2 * global_lt,), "<f8")
    temporal_sign[:] = -1
    temporal_sign[half_t : half_t + global_lt] = 1

    projector_local = cp.roll(parity_projector, t_src, 0)[latt_info.gt * latt_info.Lt : (latt_info.gt + 1) * latt_info.Lt]
    sign_local = temporal_sign[global_lt - t_src : 2 * global_lt - t_src][latt_info.gt * latt_info.Lt : (latt_info.gt + 1) * latt_info.Lt]
    proton = cp.zeros((latt_info.Lt,), "<c16")
    proton_data = propagator.data
    for a, b, c in permutations(tuple(range(3))):
        for d, e, f in permutations(tuple(range(3))):
            sign = 1 if b == (a + 1) % 3 else -1
            sign *= 1 if e == (d + 1) % 3 else -1
            proton += (sign * sign_local) * (
                contract(
                    "ij,kl,tmn,wtzyxik,wtzyxjl,wtzyxmn->t",
                    c_matrix @ gamma5,
                    c_matrix @ gamma5,
                    projector_local,
                    proton_data[:, :, :, :, :, :, :, a, d],
                    proton_data[:, :, :, :, :, :, :, b, e],
                    proton_data[:, :, :, :, :, :, :, c, f],
                )
                + contract(
                    "ij,kl,tmn,wtzyxik,wtzyxjn,wtzyxml->t",
                    c_matrix @ gamma5,
                    c_matrix @ gamma5,
                    projector_local,
                    proton_data[:, :, :, :, :, :, :, a, d],
                    proton_data[:, :, :, :, :, :, :, b, e],
                    proton_data[:, :, :, :, :, :, :, c, f],
                )
            )
    return proton


def main() -> None:
    _validate_handoff_contract()
    if not GAUGE_PATH.exists():
        raise FileNotFoundError(f"Gauge configuration not found: {GAUGE_PATH}")

    np, cp, _, core, _, io = _load_runtime_modules()
    _print_handoff_summary()
    core.init(GRID_SIZE, LATTICE_SIZE, resource_path=RESOURCE_PATH)
    latt_info = core.LatticeInfo(LATTICE_SIZE, -1, XI_0 / NU)
    dirac = core.getDirac(latt_info, MASS, SOLVER_TOL, SOLVER_MAXITER, XI_0, COEFF_T, COEFF_R, MULTIGRID_BLOCKS)

    start = perf_counter()
    gauge = io.readChromaQIOGauge(str(GAUGE_PATH))
    gauge.stoutSmear(STOUT_SMEAR_STEPS, STOUT_SMEAR_RHO, STOUT_SMEAR_NDIM)
    if latt_info.mpi_rank == 0:
        print(f"Loaded and stout-smeared gauge from {GAUGE_PATH} in {perf_counter() - start:.2f} sec")

    global_lt = LATTICE_SIZE[3]
    proton = cp.zeros((len(SOURCE_TIMESLICES), latt_info.Lt), "<c16")
    dirac.loadGauge(gauge)
    try:
        for t_idx, t_src in enumerate(SOURCE_TIMESLICES):
            invert_start = perf_counter()
            propagator = core.invert(dirac, "wall", t_src)
            if latt_info.mpi_rank == 0:
                print(f"Inversion for wall source at t={t_src} took {perf_counter() - invert_start:.2f} sec")
            proton[t_idx] = contract_proton_zero_momentum(propagator, latt_info, t_src, global_lt)
    finally:
        dirac.freeGauge()

    gathered = core.gatherLattice(proton.real.get(), [1, -1, -1, -1])
    if latt_info.mpi_rank == 0:
        for t_idx, t_src in enumerate(SOURCE_TIMESLICES):
            gathered[t_idx] = np.roll(gathered[t_idx], -t_src, 0)
        CORRELATOR_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        np.save(CORRELATOR_OUTPUT, gathered)
        print(f"Saved proton 2pt correlator array to {CORRELATOR_OUTPUT}")
        print("Workflow references:")
        print("- /Users/zhaodianjun/PyQUDA/examples/3_Pion_Proton_2pt.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_io.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/io/__init__.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/source.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/core.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/gamma.py")


if __name__ == "__main__":
    main()
