#!/usr/bin/env python3
"""Complete runnable pion PCAC workflow generated by pyquda-agent."""

from __future__ import annotations

from pathlib import Path
from time import perf_counter

# Fixed workflow: gauge -> stout-smear -> getDirac(multigrid) -> wall source -> pion / pionA4 zero-momentum contractions -> PCAC ratio -> npy.
# Review the sibling .physics.json, .task.json, and .plan.json artifacts before treating this script as complete.
# HPC handoff contract:
# - launch mode assumption: local
# - gauge input is expected on a filesystem visible to all ranks
# - only rank 0 writes the final correlator artifact
# - this script assumes the target environment already provides PyQUDA, QUDA, CuPy, opt_einsum, and MPI layout support

WORKFLOW_ID = 'pion_pcac_chroma_wall_local_zero_momentum_npy_v1'
SCRIPT_PATH = Path(__file__).resolve()
TASK_ARTIFACT = SCRIPT_PATH.with_suffix(".task.json")
PHYSICS_ARTIFACT = SCRIPT_PATH.with_suffix(".physics.json")
PLAN_ARTIFACT = SCRIPT_PATH.with_suffix(".plan.json")
PROBE_ARTIFACT = SCRIPT_PATH.with_suffix(".probe.json")
GAUGE_PATH = Path('/Users/zhaodianjun/PyQUDA/tests/weak_field.lime')
CORRELATOR_OUTPUT = Path('/Users/zhaodianjun/pyquda-agent/outputs/pion_pcac.npy')
RESOURCE_PATH = '.cache/quda'
CLUSTER_LAUNCH = 'local'
GAUGE_FORMAT = 'chroma_qio'
SOURCE_TYPE = 'wall'
SINK_TYPE = 'local'
GRID_SIZE = [1, 1, 1, 1]
LATTICE_SIZE = [4, 4, 4, 8]
SOURCE_TIMESLICES = [0]
MASS = -0.277
XI_0 = 1.0
NU = 1.0
COEFF_T = 1.160920226
COEFF_R = 1.160920226
SOLVER_TOL = 1e-12
SOLVER_MAXITER = 1000
MULTIGRID_BLOCKS = [[6, 6, 6, 4], [4, 4, 4, 9]]
STOUT_SMEAR_STEPS = 1
STOUT_SMEAR_RHO = 0.125
STOUT_SMEAR_NDIM = 4


def _validate_handoff_contract() -> None:
    expected_suffixes = {".lime", ".xml"}
    if GAUGE_FORMAT != "chroma_qio":
        raise ValueError(f"Current pion PCAC workflow requires GAUGE_FORMAT='chroma_qio'; got {GAUGE_FORMAT!r}")
    if GAUGE_PATH.suffix not in expected_suffixes:
        raise ValueError(
            f"Expected a Chroma/QIO gauge path ending in one of {sorted(expected_suffixes)}; got {GAUGE_PATH}"
        )
    if SOURCE_TYPE != "wall":
        raise ValueError(f"Current pion PCAC workflow requires SOURCE_TYPE='wall'; got {SOURCE_TYPE!r}")
    if SINK_TYPE != "local":
        raise ValueError(f"Current pion PCAC workflow requires SINK_TYPE='local'; got {SINK_TYPE!r}")
    if CORRELATOR_OUTPUT.suffix != ".npy":
        raise ValueError(f"Expected a .npy correlator output path; got {CORRELATOR_OUTPUT}")
    if len(LATTICE_SIZE) != 4 or len(GRID_SIZE) != 4:
        raise ValueError("LATTICE_SIZE and GRID_SIZE must both contain exactly four integers.")
    if any(value <= 0 for value in LATTICE_SIZE):
        raise ValueError(f"LATTICE_SIZE must be strictly positive; got {LATTICE_SIZE}")
    if any(value <= 0 for value in GRID_SIZE):
        raise ValueError(f"GRID_SIZE must be strictly positive; got {GRID_SIZE}")
    for axis, (latt_extent, grid_extent) in enumerate(zip(LATTICE_SIZE, GRID_SIZE, strict=True)):
        if latt_extent % grid_extent != 0:
            raise ValueError(
                f"LATTICE_SIZE[{axis}]={latt_extent} must be divisible by GRID_SIZE[{axis}]={grid_extent}"
            )
    if not SOURCE_TIMESLICES:
        raise ValueError("At least one source timeslice is required.")
    global_lt = LATTICE_SIZE[3]
    invalid_timeslices = [t_src for t_src in SOURCE_TIMESLICES if t_src < 0 or t_src >= global_lt]
    if invalid_timeslices:
        raise ValueError(
            f"All source timeslices must satisfy 0 <= t_src < {global_lt}; got {invalid_timeslices}"
        )
    if not MULTIGRID_BLOCKS or any(not block or any(item <= 0 for item in block) for block in MULTIGRID_BLOCKS):
        raise ValueError("MULTIGRID_BLOCKS must contain only positive block extents.")
    if STOUT_SMEAR_STEPS is None or STOUT_SMEAR_STEPS <= 0:
        raise ValueError("STOUT_SMEAR_STEPS must be strictly positive.")
    if STOUT_SMEAR_RHO is None or STOUT_SMEAR_RHO <= 0.0:
        raise ValueError("STOUT_SMEAR_RHO must be positive.")
    if STOUT_SMEAR_NDIM is None or STOUT_SMEAR_NDIM <= 0:
        raise ValueError("STOUT_SMEAR_NDIM must be strictly positive.")
    if not RESOURCE_PATH:
        raise ValueError("RESOURCE_PATH must be a non-empty string.")
    if not CLUSTER_LAUNCH:
        raise ValueError("CLUSTER_LAUNCH must be a non-empty string.")
    if not TASK_ARTIFACT.exists() or not PHYSICS_ARTIFACT.exists() or not PLAN_ARTIFACT.exists():
        raise FileNotFoundError(
            "Expected sibling review artifacts next to this script: "
            f"{PHYSICS_ARTIFACT.name}, {TASK_ARTIFACT.name}, and {PLAN_ARTIFACT.name}"
        )


def _print_handoff_summary() -> None:
    print(f"Workflow ID: {WORKFLOW_ID}")
    print(f"Launch assumption: {CLUSTER_LAUNCH}")
    print(f"Gauge input path: {GAUGE_PATH}")
    print(f"Correlator output path: {CORRELATOR_OUTPUT}")
    print(f"Gauge format contract: {GAUGE_FORMAT}")
    print(f"Source/sink contract: {SOURCE_TYPE} -> {SINK_TYPE}")
    print(f"Source timeslices: {SOURCE_TIMESLICES}")
    print(f"Stout smear contract: steps={STOUT_SMEAR_STEPS}, rho={STOUT_SMEAR_RHO}, ndim={STOUT_SMEAR_NDIM}")
    print(f"Multigrid blocks: {MULTIGRID_BLOCKS}")
    print(f"QUDA resource path assumption: {RESOURCE_PATH}")
    print(f"Physics artifact: {PHYSICS_ARTIFACT}")
    print(f"Structured task artifact: {TASK_ARTIFACT}")
    print(f"Implementation plan artifact: {PLAN_ARTIFACT}")
    print(f"Probe artifact path: {PROBE_ARTIFACT}")
    print("Filesystem contract: gauge input must be visible to all ranks; only rank 0 writes output.")
    print("Submission assumption: launch under the MPI/GPU layout encoded by GRID_SIZE.")
    print("Output contract: save a three-channel array ordered as [pion, pionA4, ratio].")
    print("Dependency contract: numpy, cupy, pyquda_utils, and pyquda must import before heavy work starts.")
    print("Layout contract: lattice extents must be divisible by the requested QUDA/MPI grid.")


def _load_runtime_modules():
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'numpy'. Activate a PyQUDA Python environment with NumPy installed before running this script."
        ) from exc

    try:
        import cupy as cp
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'cupy'. Activate a PyQUDA environment with CuPy installed before running this script."
        ) from exc

    try:
        from opt_einsum import contract
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'opt_einsum'. Activate a PyQUDA environment with opt_einsum installed before running this script."
        ) from exc

    try:
        from pyquda_utils import core, gamma, io
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda_utils'. If you are running from a local PyQUDA checkout, build/install PyQUDA first "
            "or export PYTHONPATH=~/PyQUDA after following the upstream development instructions."
        ) from exc

    try:
        import pyquda  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda'. The PyQUDA core bindings are not available in this Python environment."
        ) from exc

    return np, cp, contract, core, gamma, io


def main() -> None:
    _validate_handoff_contract()
    if not GAUGE_PATH.exists():
        raise FileNotFoundError(f"Gauge configuration not found: {GAUGE_PATH}")

    np, cp, contract, core, gamma, io = _load_runtime_modules()
    _print_handoff_summary()
    core.init(GRID_SIZE, resource_path=RESOURCE_PATH)
    latt_info = core.LatticeInfo(LATTICE_SIZE, -1, XI_0 / NU)
    dirac = core.getDirac(latt_info, MASS, SOLVER_TOL, SOLVER_MAXITER, XI_0, COEFF_T, COEFF_R, MULTIGRID_BLOCKS)
    gamma4 = gamma.gamma(8)
    gamma5 = gamma.gamma(15)

    start = perf_counter()
    gauge = io.readChromaQIOGauge(str(GAUGE_PATH))
    gauge.stoutSmear(STOUT_SMEAR_STEPS, STOUT_SMEAR_RHO, STOUT_SMEAR_NDIM)
    if latt_info.mpi_rank == 0:
        print(f"Loaded and stout-smeared gauge from {GAUGE_PATH} in {perf_counter() - start:.2f} sec")

    pion = cp.zeros((len(SOURCE_TIMESLICES), latt_info.Lt), "<c16")
    pion_a4 = cp.zeros((len(SOURCE_TIMESLICES), latt_info.Lt), "<c16")

    dirac.loadGauge(gauge)
    for t_idx, t_src in enumerate(SOURCE_TIMESLICES):
        invert_start = perf_counter()
        propagator = core.invert(dirac, "wall", t_src)
        if latt_info.mpi_rank == 0:
            print(f"Inversion for wall source at t={t_src} took {perf_counter() - invert_start:.2f} sec")

        pion[t_idx] += contract(
            "wtzyxjiba,jk,wtzyxklba,li->t",
            propagator.data.conj(),
            gamma5 @ gamma5,
            propagator.data,
            gamma5 @ gamma5,
        )
        pion_a4[t_idx] += contract(
            "wtzyxjiba,jk,wtzyxklba,li->t",
            propagator.data.conj(),
            gamma5 @ gamma5 @ gamma4,
            propagator.data,
            gamma5 @ gamma5,
        )
    dirac.freeGauge()

    gathered_pion = core.gatherLattice(pion.real.get(), [1, -1, -1, -1])
    gathered_pion_a4 = core.gatherLattice(pion_a4.real.get(), [1, -1, -1, -1])
    if latt_info.mpi_rank == 0:
        for t_idx, t_src in enumerate(SOURCE_TIMESLICES):
            gathered_pion[t_idx] = np.roll(gathered_pion[t_idx], -t_src, 0)
            gathered_pion_a4[t_idx] = np.roll(gathered_pion_a4[t_idx], -t_src, 0)
        twopt = gathered_pion.mean(0)
        twopt_a4 = gathered_pion_a4.mean(0)
        ratio = np.divide(twopt_a4, twopt, out=np.zeros_like(twopt_a4), where=np.abs(twopt) > 0.0)
        payload = np.stack([twopt, twopt_a4, ratio], axis=0)
        CORRELATOR_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        np.save(CORRELATOR_OUTPUT, payload)
        print(f"Saved pion PCAC correlator bundle to {CORRELATOR_OUTPUT}")
        print("Channel order: [pion, pionA4, ratio]")
        print("Workflow references:")
        print("- /Users/zhaodianjun/PyQUDA/examples/4_Pion_PCAC.py")
        print("- /Users/zhaodianjun/PyQUDA/examples/3_Pion_Proton_2pt.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_io.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/io/__init__.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/core.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/gamma.py")


if __name__ == "__main__":
    main()
