#!/usr/bin/env python3
"""Complete runnable meson-spectroscopy workflow generated by pyquda-agent."""

from __future__ import annotations

from pathlib import Path
from time import perf_counter

# Fixed workflow: gauge -> Clover -> wall source -> fixed gamma5/gamma4gamma5 insertion family -> grounded |p|^2<=9 momentum family -> npy.
# Review the sibling .physics.json, .task.json, and .plan.json artifacts before treating this script as complete.
# HPC handoff contract:
# - launch mode assumption: local
# - gauge input is expected on a filesystem visible to all ranks
# - this workflow is only grounded for GRID_SIZE[3] == 1 because the local reference path stores the full source-timeslice sweep on one temporal rank
# - only rank 0 writes the final correlator artifact
# - this script assumes the target environment already provides PyQUDA, QUDA, CuPy, and MPI layout support

WORKFLOW_ID = 'meson_spec_chroma_wall_gamma5_axial_mom2max9_npy_v1'
SCRIPT_PATH = Path(__file__).resolve()
TASK_ARTIFACT = SCRIPT_PATH.with_suffix(".task.json")
PHYSICS_ARTIFACT = SCRIPT_PATH.with_suffix(".physics.json")
PLAN_ARTIFACT = SCRIPT_PATH.with_suffix(".plan.json")
GAUGE_PATH = Path('/Users/zhaodianjun/PyQUDA/tests/weak_field.lime')
CORRELATOR_OUTPUT = Path('/Users/zhaodianjun/pyquda-agent/outputs/meson_spec.npy')
RESOURCE_PATH = '.cache/quda'
CLUSTER_LAUNCH = 'local'
GAUGE_FORMAT = 'chroma_qio'
SOURCE_TYPE = 'wall'
SINK_TYPE = 'local'
GRID_SIZE = [1, 1, 1, 1]
LATTICE_SIZE = [4, 4, 4, 8]
MOMENTUM_LIST = [[0, 0, -3], [-1, -2, -2], [0, -2, -2], [1, -2, -2], [-2, -1, -2], [-1, -1, -2], [0, -1, -2], [1, -1, -2], [2, -1, -2], [-2, 0, -2], [-1, 0, -2], [0, 0, -2], [1, 0, -2], [2, 0, -2], [-2, 1, -2], [-1, 1, -2], [0, 1, -2], [1, 1, -2], [2, 1, -2], [-1, 2, -2], [0, 2, -2], [1, 2, -2], [-2, -2, -1], [-1, -2, -1], [0, -2, -1], [1, -2, -1], [2, -2, -1], [-2, -1, -1], [-1, -1, -1], [0, -1, -1], [1, -1, -1], [2, -1, -1], [-2, 0, -1], [-1, 0, -1], [0, 0, -1], [1, 0, -1], [2, 0, -1], [-2, 1, -1], [-1, 1, -1], [0, 1, -1], [1, 1, -1], [2, 1, -1], [-2, 2, -1], [-1, 2, -1], [0, 2, -1], [1, 2, -1], [2, 2, -1], [0, -3, 0], [-2, -2, 0], [-1, -2, 0], [0, -2, 0], [1, -2, 0], [2, -2, 0], [-2, -1, 0], [-1, -1, 0], [0, -1, 0], [1, -1, 0], [2, -1, 0], [-3, 0, 0], [-2, 0, 0], [-1, 0, 0], [0, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [-2, 1, 0], [-1, 1, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [-2, 2, 0], [-1, 2, 0], [0, 2, 0], [1, 2, 0], [2, 2, 0], [0, 3, 0], [-2, -2, 1], [-1, -2, 1], [0, -2, 1], [1, -2, 1], [2, -2, 1], [-2, -1, 1], [-1, -1, 1], [0, -1, 1], [1, -1, 1], [2, -1, 1], [-2, 0, 1], [-1, 0, 1], [0, 0, 1], [1, 0, 1], [2, 0, 1], [-2, 1, 1], [-1, 1, 1], [0, 1, 1], [1, 1, 1], [2, 1, 1], [-2, 2, 1], [-1, 2, 1], [0, 2, 1], [1, 2, 1], [2, 2, 1], [-1, -2, 2], [0, -2, 2], [1, -2, 2], [-2, -1, 2], [-1, -1, 2], [0, -1, 2], [1, -1, 2], [2, -1, 2], [-2, 0, 2], [-1, 0, 2], [0, 0, 2], [1, 0, 2], [2, 0, 2], [-2, 1, 2], [-1, 1, 2], [0, 1, 2], [1, 1, 2], [2, 1, 2], [-1, 2, 2], [0, 2, 2], [1, 2, 2], [0, 0, 3]]
GAMMA_INSERTION_LABELS = ['gamma5_gamma5', 'gamma4gamma5_gamma4gamma5']
MASS = 0.09253
XI_0 = 4.8965
NU = 0.86679
COEFF_T = 0.8549165664
COEFF_R = 2.32582045
SOLVER_TOL = 1e-12
SOLVER_MAXITER = 1000


def _validate_handoff_contract() -> None:
    expected_suffixes = {".lime", ".xml"}
    if GAUGE_FORMAT != "chroma_qio":
        raise ValueError(f"Current meson-spectroscopy workflow requires GAUGE_FORMAT='chroma_qio'; got {GAUGE_FORMAT!r}")
    if GAUGE_PATH.suffix not in expected_suffixes:
        raise ValueError(
            f"Expected a Chroma/QIO gauge path ending in one of {sorted(expected_suffixes)}; got {GAUGE_PATH}"
        )
    if SOURCE_TYPE != "wall":
        raise ValueError(f"Current meson-spectroscopy workflow requires SOURCE_TYPE='wall'; got {SOURCE_TYPE!r}")
    if SINK_TYPE != "local":
        raise ValueError(f"Current meson-spectroscopy workflow requires SINK_TYPE='local'; got {SINK_TYPE!r}")
    if CORRELATOR_OUTPUT.suffix != ".npy":
        raise ValueError(f"Expected a .npy correlator output path; got {CORRELATOR_OUTPUT}")
    if len(LATTICE_SIZE) != 4 or len(GRID_SIZE) != 4:
        raise ValueError("LATTICE_SIZE and GRID_SIZE must both contain exactly four integers.")
    if any(value <= 0 for value in LATTICE_SIZE):
        raise ValueError(f"LATTICE_SIZE must be strictly positive; got {LATTICE_SIZE}")
    if any(value <= 0 for value in GRID_SIZE):
        raise ValueError(f"GRID_SIZE must be strictly positive; got {GRID_SIZE}")
    for axis, (latt_extent, grid_extent) in enumerate(zip(LATTICE_SIZE, GRID_SIZE, strict=True)):
        if latt_extent % grid_extent != 0:
            raise ValueError(
                f"LATTICE_SIZE[{axis}]={latt_extent} must be divisible by GRID_SIZE[{axis}]={grid_extent}"
            )
    if GRID_SIZE[3] != 1:
        raise ValueError(
            f"Current meson-spectroscopy workflow is only grounded for GRID_SIZE[3] == 1; got {GRID_SIZE[3]}"
        )
    if not MOMENTUM_LIST:
        raise ValueError("MOMENTUM_LIST must be non-empty.")
    if any(len(mom) != 3 for mom in MOMENTUM_LIST):
        raise ValueError("Each momentum vector must contain exactly three integers.")
    if len(GAMMA_INSERTION_LABELS) != 2:
        raise ValueError("Current meson-spectroscopy workflow requires exactly two fixed gamma insertions.")
    if GAMMA_INSERTION_LABELS != ["gamma5_gamma5", "gamma4gamma5_gamma4gamma5"]:
        raise ValueError(
            "Current meson-spectroscopy workflow requires GAMMA_INSERTION_LABELS == ['gamma5_gamma5', 'gamma4gamma5_gamma4gamma5']."
        )
    if not RESOURCE_PATH:
        raise ValueError("RESOURCE_PATH must be a non-empty string.")
    if not TASK_ARTIFACT.exists() or not PHYSICS_ARTIFACT.exists() or not PLAN_ARTIFACT.exists():
        raise FileNotFoundError(
            "Expected sibling review artifacts next to this script: "
            f"{PHYSICS_ARTIFACT.name}, {TASK_ARTIFACT.name}, and {PLAN_ARTIFACT.name}"
        )


def _print_handoff_summary() -> None:
    print(f"Workflow ID: {WORKFLOW_ID}")
    print(f"Launch assumption: {CLUSTER_LAUNCH}")
    print(f"Gauge input path: {GAUGE_PATH}")
    print(f"Correlator output path: {CORRELATOR_OUTPUT}")
    print(f"Fixed gamma insertion family: {GAMMA_INSERTION_LABELS}")
    print(f"Momentum family size: {len(MOMENTUM_LIST)}")
    print(f"QUDA resource path assumption: {RESOURCE_PATH}")
    print(f"Physics artifact: {PHYSICS_ARTIFACT}")
    print(f"Structured task artifact: {TASK_ARTIFACT}")
    print(f"Implementation plan artifact: {PLAN_ARTIFACT}")
    print("Filesystem contract: gauge input must be visible to all ranks; only rank 0 writes output.")
    print("Layout contract: this grounded mesonspec path assumes GRID_SIZE[3] == 1 and lattice extents divisible by the requested QUDA/MPI grid.")


def _load_runtime_modules():
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'numpy'. Activate a PyQUDA Python environment with NumPy installed before running this script."
        ) from exc

    try:
        import cupy as cp
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'cupy'. Activate a PyQUDA environment with CuPy installed before running this script."
        ) from exc

    try:
        from pyquda_utils import core, gamma, io, phase
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda_utils'. If you are running from a local PyQUDA checkout, build/install PyQUDA first "
            "or export PYTHONPATH=~/PyQUDA after following the upstream development instructions."
        ) from exc

    try:
        import pyquda  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda'. The PyQUDA core bindings are not available in this Python environment."
        ) from exc

    return np, cp, core, gamma, io, phase


def _gamma_insertion_family(gamma):
    gamma5 = gamma.gamma(15)
    gamma4 = gamma.gamma(8)
    return [
        ("gamma5_gamma5", gamma5, gamma5),
        ("gamma4gamma5_gamma4gamma5", gamma4 @ gamma5, gamma4 @ gamma5),
    ]


def main() -> None:
    _validate_handoff_contract()
    if not GAUGE_PATH.exists():
        raise FileNotFoundError(f"Gauge configuration not found: {GAUGE_PATH}")

    np, cp, core, gamma, io, phase = _load_runtime_modules()
    _print_handoff_summary()
    core.init(GRID_SIZE, LATTICE_SIZE, resource_path=RESOURCE_PATH)
    latt_info = core.LatticeInfo(LATTICE_SIZE, -1, XI_0 / NU)
    dirac = core.getClover(latt_info, MASS, SOLVER_TOL, SOLVER_MAXITER, XI_0, COEFF_T, COEFF_R)
    gamma5 = gamma.gamma(15)
    vol = latt_info.volume
    ns = 4
    nc = 3
    global_lt = LATTICE_SIZE[3]
    insertion_family = _gamma_insertion_family(gamma)
    momentum_phase = phase.MomentumPhase(latt_info)
    phase_list = momentum_phase.getPhases(MOMENTUM_LIST)
    meson_spec = np.zeros((global_lt, global_lt, len(insertion_family), len(MOMENTUM_LIST)), "<c16")

    start = perf_counter()
    gauge = io.readQIOGauge(str(GAUGE_PATH))
    if latt_info.mpi_rank == 0:
        print(f"Loaded gauge from {GAUGE_PATH} in {perf_counter() - start:.2f} sec")

    with dirac.useGauge(gauge):
        for t_src in range(global_lt):
            invert_start = perf_counter()
            propagator = core.invert(dirac, "wall", t_src)
            if latt_info.mpi_rank == 0:
                print(f"Inversion for wall source at t={t_src} took {perf_counter() - invert_start:.2f} sec")

            contract_start = perf_counter()
            reshaped = propagator.data.reshape(vol, ns, ns, nc, nc)
            for gamma_idx, (label, gamma_src, gamma_snk) in enumerate(insertion_family):
                tmp = cp.einsum(
                    "ij,xkjba,kl,xliba->x",
                    gamma_src @ gamma5,
                    reshaped.conj(),
                    gamma5 @ gamma_snk,
                    reshaped,
                    optimize=True,
                )
                tmp_lattice = tmp.reshape(2, latt_info.Lt, latt_info.Lz, latt_info.Ly, latt_info.Lx // 2)
                for mom_idx, mom_phase in enumerate(phase_list):
                    correlator = cp.einsum("wtzyx,wtzyx->t", mom_phase, tmp_lattice, optimize=True)
                    correlator = cp.roll(correlator, -t_src)
                    gathered = core.gatherLattice(correlator.get(), [0, -1, -1, -1])
                    if latt_info.mpi_rank == 0:
                        meson_spec[t_src, :, gamma_idx, mom_idx] = gathered
            if latt_info.mpi_rank == 0:
                print(f"Contraction for {len(insertion_family)} gamma insertions at t={t_src} took {perf_counter() - contract_start:.2f} sec")

    if latt_info.mpi_rank == 0:
        CORRELATOR_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        np.save(CORRELATOR_OUTPUT, meson_spec)
        print(f"Saved meson spectroscopy correlator tensor to {CORRELATOR_OUTPUT}")
        print("Workflow references:")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_mesonspec.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_io.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/io/__init__.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/core.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/gamma.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/phase.py")


if __name__ == "__main__":
    main()
