#!/usr/bin/env python3
"""Complete runnable pion two-point workflow generated by pyquda-agent."""

from __future__ import annotations

from pathlib import Path
from time import perf_counter

# Fixed workflow: gauge -> Clover inversion -> wall source -> local sink -> zero momentum -> npy.
# Review the sibling .task.json and .plan.json artifacts before treating this script as complete.

GAUGE_PATH = Path('/Users/zhaodianjun/PyQUDA/tests/weak_field.lime')
CORRELATOR_OUTPUT = Path('/Users/zhaodianjun/pyquda-agent/outputs/pion_api.npy')
RESOURCE_PATH = '.cache/quda'
GRID_SIZE = [1, 1, 1, 1]
LATTICE_SIZE = [4, 4, 4, 8]
SOURCE_TIMESLICES = [0]
MASS = 0.09253
XI_0 = 4.8965
NU = 0.86679
COEFF_T = 0.8549165664
COEFF_R = 2.32582045
SOLVER_TOL = 1e-12
SOLVER_MAXITER = 1000


def _load_runtime_modules():
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'numpy'. Activate a PyQUDA Python environment with NumPy installed before running this script."
        ) from exc

    try:
        import cupy as cp
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'cupy'. Activate a PyQUDA environment with CuPy installed before running this script."
        ) from exc

    try:
        from pyquda_utils import core, gamma, io
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda_utils'. If you are running from a local PyQUDA checkout, build/install PyQUDA first "
            "or export PYTHONPATH=~/PyQUDA after following the upstream development instructions."
        ) from exc

    try:
        import pyquda  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda'. The PyQUDA core bindings are not available in this Python environment."
        ) from exc

    return np, cp, core, gamma, io


def contract_pion_zero_momentum(propagator, latt_info, t_src):
    _, cp, _, gamma, _ = _load_runtime_modules()
    gamma5 = gamma.gamma(15)
    vol = latt_info.volume
    nc = 3
    ns = 4
    tmp = cp.einsum(
        "ij,xkjba,kl,xliba->x",
        gamma5 @ gamma5,
        propagator.data.reshape(vol, ns, ns, nc, nc).conj(),
        gamma5 @ gamma5,
        propagator.data.reshape(vol, ns, ns, nc, nc),
        optimize=True,
    )
    correlator = cp.einsum(
        "wtzyx->t",
        tmp.reshape(2, latt_info.Lt, latt_info.Lz, latt_info.Ly, latt_info.Lx // 2),
        optimize=True,
    )
    return cp.roll(correlator, -t_src)


def main() -> None:
    if not GAUGE_PATH.exists():
        raise FileNotFoundError(f"Gauge configuration not found: {GAUGE_PATH}")

    np, cp, core, _, io = _load_runtime_modules()
    core.init(GRID_SIZE, LATTICE_SIZE, resource_path=RESOURCE_PATH)
    latt_info = core.LatticeInfo(LATTICE_SIZE, -1, XI_0 / NU)
    dirac = core.getClover(latt_info, MASS, SOLVER_TOL, SOLVER_MAXITER, XI_0, COEFF_T, COEFF_R)

    start = perf_counter()
    gauge = io.readQIOGauge(str(GAUGE_PATH))
    if latt_info.mpi_rank == 0:
        print(f"Loaded gauge from {GAUGE_PATH} in {perf_counter() - start:.2f} sec")

    lt = latt_info.Lt * (GRID_SIZE[3] if GRID_SIZE[3] is not None else 1)
    twopt = np.zeros((len(SOURCE_TIMESLICES), lt), dtype=np.float64)

    with dirac.useGauge(gauge):
        for idx, t_src in enumerate(SOURCE_TIMESLICES):
            invert_start = perf_counter()
            propagator = core.invert(dirac, "wall", t_src)
            if latt_info.mpi_rank == 0:
                print(f"Inversion for wall source at t={t_src} took {perf_counter() - invert_start:.2f} sec")

            corr_local = contract_pion_zero_momentum(propagator, latt_info, t_src)
            corr_global = core.gatherLattice(corr_local.real.get(), [0, -1, -1, -1])
            if latt_info.mpi_rank == 0:
                twopt[idx] = corr_global

    if latt_info.mpi_rank == 0:
        CORRELATOR_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        np.save(CORRELATOR_OUTPUT, twopt)
        print(f"Saved pion 2pt correlator to {CORRELATOR_OUTPUT}")
        print(f"Cluster/runtime assumption: local")
        print("Workflow references:")
        print("- /Users/zhaodianjun/PyQUDA/examples/3_Pion_Proton_2pt.py")
        print("- /Users/zhaodianjun/PyQUDA/examples/5_Pion_Dispersion.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_mesonspec.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_io.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/io/__init__.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/source.py")


if __name__ == "__main__":
    main()
