#!/usr/bin/env python3
"""Complete runnable pion PCAC workflow from existing propagators generated by pyquda-agent."""

from __future__ import annotations

import os
from pathlib import Path

# Fixed workflow: existing wall-source propagator(s) -> zero-momentum pion/pionA4 contractions -> PCAC ratio -> npy.
# Review the sibling .physics.json, .task.json, and .plan.json artifacts before treating this script as complete.
# HPC handoff contract:
# - launch mode assumption: local
# - propagator inputs are expected on a filesystem visible to all ranks
# - the stored propagators must already come from a compatible wall-source pion-PCAC path on the stated lattice/grid
# - this branch does not regenerate propagators or apply gauge smearing; it only performs the grounded contraction step
# - only rank 0 writes the final correlator artifact
# - this script assumes the target environment already provides PyQUDA, QUDA, CuPy, opt_einsum, and MPI layout support

WORKFLOW_ID = 'pion_pcac_existing_propagator_local_zero_momentum_npy_v1'
SCRIPT_PATH = Path(__file__).resolve()
TASK_ARTIFACT = SCRIPT_PATH.with_suffix(".task.json")
PHYSICS_ARTIFACT = SCRIPT_PATH.with_suffix(".physics.json")
PLAN_ARTIFACT = SCRIPT_PATH.with_suffix(".plan.json")
PROBE_ARTIFACT = SCRIPT_PATH.with_suffix(".probe.json")
PROPAGATOR_PATHS = ['/tmp/pcac_prop_0.npy']
PROPAGATOR_FORMAT = 'npy'
SOURCE_TYPE = 'wall'
SINK_TYPE = 'local'
SOURCE_TIMESLICES = [0]
CORRELATOR_OUTPUT = Path('/Users/zhaodianjun/pyquda-agent/outputs/validate_pion_pcac_existing_propagator.npy')
RESOURCE_PATH = '.cache/quda'
CLUSTER_LAUNCH = 'local'
GRID_SIZE = [1, 1, 1, 1]
LATTICE_SIZE = [4, 4, 4, 8]
GAUGE_FIXED = False


def _resolved_propagator_paths():
    return [Path(path).expanduser().resolve() for path in PROPAGATOR_PATHS]


def _nearest_existing_parent(path: Path) -> Path:
    current = path.expanduser().resolve().parent
    while not current.exists() and current != current.parent:
        current = current.parent
    return current


def _validate_output_parent_writable(path: Path, *, label: str) -> None:
    writable_probe = _nearest_existing_parent(path)
    if not writable_probe.exists():
        raise FileNotFoundError(f"Unable to locate an existing parent directory for {label} path {path}")
    if not os.access(writable_probe, os.W_OK):
        raise PermissionError(
            f"{label} path {path} requires a writable parent directory on the submission filesystem; "
            f"nearest existing parent is {writable_probe}"
        )


def _propagator_input_dirs():
    return sorted({str(path.parent) for path in _resolved_propagator_paths()})


def _propagator_manifest():
    return [
        {"index": index, "source_timeslice": t_src, "path": str(path)}
        for index, (path, t_src) in enumerate(zip(_resolved_propagator_paths(), SOURCE_TIMESLICES, strict=True))
    ]


def _validate_handoff_contract() -> None:
    if not PROPAGATOR_PATHS:
        raise ValueError("At least one propagator path is required.")
    resolved_paths = _resolved_propagator_paths()
    if len({str(path) for path in resolved_paths}) != len(resolved_paths):
        raise ValueError("Duplicate propagator paths are not allowed in the input manifest.")
    if PROPAGATOR_FORMAT not in {"npy", "hdf5", "chroma_qio"}:
        raise ValueError(
            f"Expected PROPAGATOR_FORMAT in {'npy', 'hdf5', 'chroma_qio'} for the grounded propagator-entry pion PCAC family; got {PROPAGATOR_FORMAT!r}"
        )
    if SOURCE_TYPE != "wall":
        raise ValueError(f"Current propagator-entry pion PCAC workflow requires SOURCE_TYPE='wall'; got {SOURCE_TYPE!r}")
    if SINK_TYPE != "local":
        raise ValueError(f"Current propagator-entry pion PCAC workflow requires SINK_TYPE='local'; got {SINK_TYPE!r}")
    if CORRELATOR_OUTPUT.suffix != ".npy":
        raise ValueError(f"Expected a .npy correlator output path; got {CORRELATOR_OUTPUT}")
    if any(path == CORRELATOR_OUTPUT.expanduser().resolve() for path in resolved_paths):
        raise ValueError("CORRELATOR_OUTPUT must not reuse a propagator input path.")
    if len(LATTICE_SIZE) != 4 or len(GRID_SIZE) != 4:
        raise ValueError("LATTICE_SIZE and GRID_SIZE must both contain exactly four integers.")
    if any(value <= 0 for value in LATTICE_SIZE):
        raise ValueError(f"LATTICE_SIZE must be strictly positive; got {LATTICE_SIZE}")
    if any(value <= 0 for value in GRID_SIZE):
        raise ValueError(f"GRID_SIZE must be strictly positive; got {GRID_SIZE}")
    for axis, (latt_extent, grid_extent) in enumerate(zip(LATTICE_SIZE, GRID_SIZE, strict=True)):
        if latt_extent % grid_extent != 0:
            raise ValueError(
                f"LATTICE_SIZE[{axis}]={latt_extent} must be divisible by GRID_SIZE[{axis}]={grid_extent}"
            )
    if not SOURCE_TIMESLICES:
        raise ValueError("At least one source timeslice is required for the propagator-entry pion PCAC contraction.")
    if len(SOURCE_TIMESLICES) != len(PROPAGATOR_PATHS):
        raise ValueError(
            f"Expected len(SOURCE_TIMESLICES) == len(PROPAGATOR_PATHS); got {len(SOURCE_TIMESLICES)} and {len(PROPAGATOR_PATHS)}"
        )
    global_lt = LATTICE_SIZE[3]
    invalid_timeslices = [t_src for t_src in SOURCE_TIMESLICES if t_src < 0 or t_src >= global_lt]
    if invalid_timeslices:
        raise ValueError(
            f"All source timeslices must satisfy 0 <= t_src < {global_lt}; got {invalid_timeslices}"
        )
    if GAUGE_FIXED is not False:
        raise ValueError(
            f"Current propagator-entry pion PCAC workflow is only grounded for GAUGE_FIXED=False; got {GAUGE_FIXED!r}"
        )
    if not RESOURCE_PATH:
        raise ValueError("RESOURCE_PATH must be a non-empty string.")
    if not CLUSTER_LAUNCH:
        raise ValueError("CLUSTER_LAUNCH must be a non-empty string.")
    _validate_output_parent_writable(CORRELATOR_OUTPUT, label="Correlator output")
    if not TASK_ARTIFACT.exists() or not PHYSICS_ARTIFACT.exists() or not PLAN_ARTIFACT.exists():
        raise FileNotFoundError(
            "Expected sibling review artifacts next to this script: "
            f"{PHYSICS_ARTIFACT.name}, {TASK_ARTIFACT.name}, and {PLAN_ARTIFACT.name}"
        )


def _load_runtime_modules():
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'numpy'. Activate a PyQUDA Python environment with NumPy installed before running this script."
        ) from exc
    try:
        import cupy as cp
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'cupy'. Activate a PyQUDA environment with CuPy installed before running this script."
        ) from exc
    try:
        from opt_einsum import contract
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'opt_einsum'. Activate a PyQUDA environment with opt_einsum installed before running this script."
        ) from exc
    try:
        from pyquda_utils import core, gamma, io
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda_utils'. If you are running from a local PyQUDA checkout, build/install PyQUDA first "
            "or export PYTHONPATH=~/PyQUDA after following the upstream development instructions."
        ) from exc
    try:
        import pyquda  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda'. The PyQUDA core bindings are not available in this Python environment."
        ) from exc
    return np, cp, contract, core, gamma, io


def _print_handoff_summary() -> None:
    print(f"Workflow ID: {WORKFLOW_ID}")
    print(f"Launch assumption: {CLUSTER_LAUNCH}")
    print(f"Propagator format contract: {PROPAGATOR_FORMAT}")
    print(f"Propagator paths: {PROPAGATOR_PATHS}")
    print(f"Propagator input count: {len(PROPAGATOR_PATHS)}")
    print(f"Input directories: {_propagator_input_dirs()}")
    print(f"Input manifest: {_propagator_manifest()}")
    print(f"Source/sink contract: {SOURCE_TYPE} -> {SINK_TYPE}")
    print(f"Source timeslices: {SOURCE_TIMESLICES}")
    print(f"Correlator output path: {CORRELATOR_OUTPUT}")
    print(f"Output parent directory: {CORRELATOR_OUTPUT.expanduser().resolve().parent}")
    print(f"Gauge-fixed assumption on loaded propagators: {GAUGE_FIXED}")
    print(f"QUDA resource path assumption: {RESOURCE_PATH}")
    print(f"Physics artifact: {PHYSICS_ARTIFACT}")
    print(f"Structured task artifact: {TASK_ARTIFACT}")
    print(f"Implementation plan artifact: {PLAN_ARTIFACT}")
    print(f"Probe artifact path: {PROBE_ARTIFACT}")
    print("Filesystem contract: propagator inputs must be visible to all ranks; only rank 0 writes output.")
    print("Input mutability contract: propagator inputs are treated as immutable handoff artifacts and are never overwritten.")
    print("Directory convention: prefer a dedicated writable results directory instead of writing beside stored propagator handoff artifacts.")
    print("Submission assumption: launch under the MPI/GPU layout encoded by GRID_SIZE.")
    print("Submission precheck: confirm the nearest existing parent of the correlator output path is writable before launch.")
    print("Output contract: save a three-channel array ordered as [pion, pionA4, ratio].")
    print("Dependency contract: numpy, cupy, pyquda_utils, and pyquda must import before heavy work starts.")
    print("Layout contract: lattice extents must be divisible by the requested QUDA/MPI grid.")


def _load_propagator(path, core, io):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Propagator not found: {path}")
    if PROPAGATOR_FORMAT == "npy" and path.suffix != ".npy":
        raise ValueError(f"Expected an .npy propagator path for PROPAGATOR_FORMAT='npy'; got {path}")
    if PROPAGATOR_FORMAT == "hdf5" and path.suffix not in {".h5", ".hdf5"}:
        raise ValueError(f"Expected an .h5 or .hdf5 propagator path for PROPAGATOR_FORMAT='hdf5'; got {path}")
    if False:
        return io.readNPYPropagator(str(path), 0)
    return io.readNPYPropagator(str(path))


def _contract_channels(propagator, contract, gamma):
    _, cp, _, _, _, _ = _load_runtime_modules()
    gamma4 = gamma.gamma(8)
    gamma5 = gamma.gamma(15)
    pion = contract(
        "wtzyxjiba,jk,wtzyxklba,li->t",
        propagator.data.conj(),
        gamma5 @ gamma5,
        propagator.data,
        gamma5 @ gamma5,
    )
    pion_a4 = contract(
        "wtzyxjiba,jk,wtzyxklba,li->t",
        propagator.data.conj(),
        gamma5 @ gamma5 @ gamma4,
        propagator.data,
        gamma5 @ gamma5,
    )
    return pion, pion_a4


def main() -> None:
    _validate_handoff_contract()
    np, cp, contract, core, gamma, io = _load_runtime_modules()
    _print_handoff_summary()
    core.init(GRID_SIZE, LATTICE_SIZE, resource_path=RESOURCE_PATH)
    latt_info = core.LatticeInfo(LATTICE_SIZE, -1, 1.0)
    pion = cp.zeros((len(SOURCE_TIMESLICES), latt_info.Lt), "<c16")
    pion_a4 = cp.zeros((len(SOURCE_TIMESLICES), latt_info.Lt), "<c16")

    for t_idx, (propagator_path, t_src) in enumerate(zip(PROPAGATOR_PATHS, SOURCE_TIMESLICES, strict=True)):
        propagator = _load_propagator(propagator_path, core, io)
        pion_channel, pion_a4_channel = _contract_channels(propagator, contract, gamma)
        pion[t_idx] = pion_channel
        pion_a4[t_idx] = pion_a4_channel

    gathered_pion = core.gatherLattice(pion.real.get(), [1, -1, -1, -1])
    gathered_pion_a4 = core.gatherLattice(pion_a4.real.get(), [1, -1, -1, -1])
    if latt_info.mpi_rank == 0:
        for t_idx, t_src in enumerate(SOURCE_TIMESLICES):
            gathered_pion[t_idx] = np.roll(gathered_pion[t_idx], -t_src, 0)
            gathered_pion_a4[t_idx] = np.roll(gathered_pion_a4[t_idx], -t_src, 0)
        twopt = gathered_pion.mean(0)
        twopt_a4 = gathered_pion_a4.mean(0)
        ratio = np.divide(twopt_a4, twopt, out=np.zeros_like(twopt_a4), where=np.abs(twopt) > 0.0)
        payload = np.stack([twopt, twopt_a4, ratio], axis=0)
        CORRELATOR_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        np.save(CORRELATOR_OUTPUT, payload)
        print(f"Saved pion PCAC correlator bundle to {CORRELATOR_OUTPUT}")
        print("Channel order: [pion, pionA4, ratio]")
        print("Propagator-entry workflow references:")
        print("- /Users/zhaodianjun/PyQUDA/examples/4_Pion_PCAC.py")
        print("- /Users/zhaodianjun/PyQUDA/examples/3_Pion_Proton_2pt.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_io.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/io/__init__.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/core.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/gamma.py")


if __name__ == "__main__":
    main()
