#!/usr/bin/env python3
"""Complete runnable Wilson-flow energy-history workflow generated by pyquda-agent."""

from __future__ import annotations

import os
from pathlib import Path
from time import perf_counter

# Fixed workflow: gauge -> gauge.copy() -> wilsonFlowChroma(flow_steps, flow_epsilon) -> npy energy history.
# Review the sibling .physics.json, .task.json, and .plan.json artifacts before treating this script as complete.
# HPC handoff contract:
# - launch mode assumption: local
# - gauge input is expected on a filesystem visible to all ranks
# - only rank 0 writes the final energy-history artifact
# - this script assumes the target environment already provides PyQUDA, QUDA, CuPy, and MPI layout support

WORKFLOW_ID = 'wilson_flow_chroma_qio_energy_npy_v1'
SCRIPT_PATH = Path(__file__).resolve()
TASK_ARTIFACT = SCRIPT_PATH.with_suffix(".task.json")
PHYSICS_ARTIFACT = SCRIPT_PATH.with_suffix(".physics.json")
PLAN_ARTIFACT = SCRIPT_PATH.with_suffix(".plan.json")
PROBE_ARTIFACT = SCRIPT_PATH.with_suffix(".probe.json")
GAUGE_PATH = Path('/Users/zhaodianjun/PyQUDA/tests/weak_field.lime')
ENERGY_OUTPUT = Path('/Users/zhaodianjun/pyquda-agent/outputs/validate_wilson_flow.npy')
RESOURCE_PATH = '.cache/quda'
CLUSTER_LAUNCH = 'local'
GAUGE_FORMAT = 'chroma_qio'
GRID_SIZE = [1, 1, 1, 1]
LATTICE_SIZE = [4, 4, 4, 8]
FLOW_STEPS = 100
FLOW_EPSILON = 1.0


def _nearest_existing_parent(path: Path) -> Path:
    current = path.expanduser().resolve().parent
    while not current.exists() and current != current.parent:
        current = current.parent
    return current


def _validate_output_parent_writable(path: Path, *, label: str) -> None:
    writable_probe = _nearest_existing_parent(path)
    if not writable_probe.exists():
        raise FileNotFoundError(f"Unable to locate an existing parent directory for {label} path {path}")
    if not os.access(writable_probe, os.W_OK):
        raise PermissionError(
            f"{label} path {path} requires a writable parent directory on the submission filesystem; "
            f"nearest existing parent is {writable_probe}"
        )


def _validate_handoff_contract() -> None:
    expected_suffixes = {".lime", ".xml"}
    if GAUGE_FORMAT != "chroma_qio":
        raise ValueError(f"Current Wilson-flow workflow requires GAUGE_FORMAT='chroma_qio'; got {GAUGE_FORMAT!r}")
    if GAUGE_PATH.suffix not in expected_suffixes:
        raise ValueError(
            f"Expected a Chroma/QIO gauge path ending in one of {sorted(expected_suffixes)}; got {GAUGE_PATH}"
        )
    if ENERGY_OUTPUT.suffix != ".npy":
        raise ValueError(f"Expected a .npy energy-history output path; got {ENERGY_OUTPUT}")
    if len(LATTICE_SIZE) != 4 or len(GRID_SIZE) != 4:
        raise ValueError("LATTICE_SIZE and GRID_SIZE must both contain exactly four integers.")
    if any(value <= 0 for value in LATTICE_SIZE):
        raise ValueError(f"LATTICE_SIZE must be strictly positive; got {LATTICE_SIZE}")
    if any(value <= 0 for value in GRID_SIZE):
        raise ValueError(f"GRID_SIZE must be strictly positive; got {GRID_SIZE}")
    for axis, (latt_extent, grid_extent) in enumerate(zip(LATTICE_SIZE, GRID_SIZE, strict=True)):
        if latt_extent % grid_extent != 0:
            raise ValueError(
                f"LATTICE_SIZE[{axis}]={latt_extent} must be divisible by GRID_SIZE[{axis}]={grid_extent}"
            )
    if FLOW_STEPS <= 0:
        raise ValueError(f"FLOW_STEPS must be positive; got {FLOW_STEPS}")
    if FLOW_EPSILON <= 0:
        raise ValueError(f"FLOW_EPSILON must be positive; got {FLOW_EPSILON}")
    if not RESOURCE_PATH:
        raise ValueError("RESOURCE_PATH must be a non-empty string.")
    if not CLUSTER_LAUNCH:
        raise ValueError("CLUSTER_LAUNCH must be a non-empty string.")
    _validate_output_parent_writable(ENERGY_OUTPUT, label="Energy-history output")
    if not TASK_ARTIFACT.exists() or not PHYSICS_ARTIFACT.exists() or not PLAN_ARTIFACT.exists():
        raise FileNotFoundError(
            "Expected sibling review artifacts next to this script: "
            f"{PHYSICS_ARTIFACT.name}, {TASK_ARTIFACT.name}, and {PLAN_ARTIFACT.name}"
        )


def _print_handoff_summary() -> None:
    print(f"Workflow ID: {WORKFLOW_ID}")
    print(f"Launch assumption: {CLUSTER_LAUNCH}")
    print(f"Gauge input path: {GAUGE_PATH}")
    print(f"Energy-history output path: {ENERGY_OUTPUT}")
    print(f"Output parent directory: {ENERGY_OUTPUT.expanduser().resolve().parent}")
    print(f"Gauge format contract: {GAUGE_FORMAT}")
    print(f"Flow contract: steps={FLOW_STEPS}, epsilon={FLOW_EPSILON}")
    print(f"QUDA resource path assumption: {RESOURCE_PATH}")
    print(f"Physics artifact: {PHYSICS_ARTIFACT}")
    print(f"Structured task artifact: {TASK_ARTIFACT}")
    print(f"Implementation plan artifact: {PLAN_ARTIFACT}")
    print(f"Probe artifact path: {PROBE_ARTIFACT}")
    print("Filesystem contract: gauge input must be visible to all ranks; only rank 0 writes output.")
    print("Submission assumption: launch under the MPI/GPU layout encoded by GRID_SIZE.")
    print("Submission precheck: confirm the nearest existing parent of the energy-history output path is writable before launch.")
    print("Output contract: ensure the energy-history output parent is writable by the rank that saves the final artifact.")
    print("Dependency contract: numpy, cupy, pyquda_utils, and pyquda must import before heavy work starts.")
    print("Layout contract: lattice extents must be divisible by the requested QUDA/MPI grid.")


def _load_runtime_modules():
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'numpy'. Activate a PyQUDA Python environment with NumPy installed before running this script."
        ) from exc

    try:
        import cupy as cp
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'cupy'. Activate a PyQUDA environment with CuPy installed before running this script."
        ) from exc

    try:
        from pyquda_utils import core, io
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda_utils'. If you are running from a local PyQUDA checkout, build/install PyQUDA first "
            "or export PYTHONPATH=~/PyQUDA after following the upstream development instructions."
        ) from exc

    try:
        import pyquda  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda'. The PyQUDA core bindings are not available in this Python environment."
        ) from exc

    return np, cp, core, io


def main() -> None:
    _validate_handoff_contract()
    if not GAUGE_PATH.exists():
        raise FileNotFoundError(f"Gauge configuration not found: {GAUGE_PATH}")

    np, _, core, io = _load_runtime_modules()
    _print_handoff_summary()
    core.init(GRID_SIZE, LATTICE_SIZE, resource_path=RESOURCE_PATH)

    start = perf_counter()
    gauge = io.readQIOGauge(str(GAUGE_PATH))
    gauge_wflow = gauge.copy()
    energy = gauge_wflow.wilsonFlowChroma(FLOW_STEPS, FLOW_EPSILON)
    elapsed = perf_counter() - start

    if gauge.latt_info.mpi_rank == 0:
        ENERGY_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        np.save(ENERGY_OUTPUT, np.asarray(energy))
        print(f"Computed Wilson-flow energy history in {elapsed:.2f} sec")
        print(f"Saved Wilson-flow energy history to {ENERGY_OUTPUT}")
        print("Workflow references:")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_wflow.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_io.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/io/__init__.py")


if __name__ == "__main__":
    main()
