#!/usr/bin/env python3
"""Complete runnable proton two-point workflow from existing propagators generated by pyquda-agent."""

from __future__ import annotations

from itertools import permutations
from pathlib import Path

# Fixed workflow: existing wall-source propagator(s) -> parity-projected proton contraction -> zero momentum -> npy.
# Review the sibling .physics.json, .task.json, and .plan.json artifacts before treating this script as complete.
# HPC handoff contract:
# - launch mode assumption: local
# - propagator inputs are expected on a filesystem visible to all ranks
# - the stored propagators must already come from a compatible Clover + wall-source proton path
# - this branch does not regenerate propagators or apply gauge smearing; it only performs the grounded contraction step
# - only rank 0 writes the final correlator artifact
# - this script assumes the target environment already provides PyQUDA, QUDA, CuPy, opt_einsum, and MPI layout support

WORKFLOW_ID = 'proton_2pt_existing_propagator_local_zero_momentum_npy_v1'
SCRIPT_PATH = Path(__file__).resolve()
TASK_ARTIFACT = SCRIPT_PATH.with_suffix(".task.json")
PHYSICS_ARTIFACT = SCRIPT_PATH.with_suffix(".physics.json")
PLAN_ARTIFACT = SCRIPT_PATH.with_suffix(".plan.json")
PROPAGATOR_PATHS = ['/tmp/proton_prop.npy']
PROPAGATOR_FORMAT = 'npy'
SOURCE_TYPE = 'wall'
SINK_TYPE = 'local'
SOURCE_TIMESLICES = [0]
CORRELATOR_OUTPUT = Path('/Users/zhaodianjun/pyquda-agent/outputs/proton_prop.npy')
RESOURCE_PATH = '.cache/quda'
CLUSTER_LAUNCH = 'local'
GRID_SIZE = [1, 1, 1, 2]
LATTICE_SIZE = [24, 24, 24, 72]
GAUGE_FIXED = False


def _validate_handoff_contract() -> None:
    if not PROPAGATOR_PATHS:
        raise ValueError("At least one propagator path is required.")
    if PROPAGATOR_FORMAT not in {"npy", "hdf5", "chroma_qio"}:
        raise ValueError(
            f"Expected PROPAGATOR_FORMAT in {'npy', 'hdf5', 'chroma_qio'} for the grounded propagator-entry proton family; got {PROPAGATOR_FORMAT!r}"
        )
    if SOURCE_TYPE != "wall":
        raise ValueError(f"Current propagator-entry proton workflow requires SOURCE_TYPE='wall'; got {SOURCE_TYPE!r}")
    if SINK_TYPE != "local":
        raise ValueError(f"Current propagator-entry proton workflow requires SINK_TYPE='local'; got {SINK_TYPE!r}")
    if CORRELATOR_OUTPUT.suffix != ".npy":
        raise ValueError(f"Expected a .npy correlator output path; got {CORRELATOR_OUTPUT}")
    if len(LATTICE_SIZE) != 4 or len(GRID_SIZE) != 4:
        raise ValueError("LATTICE_SIZE and GRID_SIZE must both contain exactly four integers.")
    if any(value <= 0 for value in LATTICE_SIZE):
        raise ValueError(f"LATTICE_SIZE must be strictly positive; got {LATTICE_SIZE}")
    if any(value <= 0 for value in GRID_SIZE):
        raise ValueError(f"GRID_SIZE must be strictly positive; got {GRID_SIZE}")
    for axis, (latt_extent, grid_extent) in enumerate(zip(LATTICE_SIZE, GRID_SIZE, strict=True)):
        if latt_extent % grid_extent != 0:
            raise ValueError(
                f"LATTICE_SIZE[{axis}]={latt_extent} must be divisible by GRID_SIZE[{axis}]={grid_extent}"
            )
    if not SOURCE_TIMESLICES:
        raise ValueError("At least one source timeslice is required for the parity-projected proton contraction.")
    if len(SOURCE_TIMESLICES) != len(PROPAGATOR_PATHS):
        raise ValueError(
            f"Expected len(SOURCE_TIMESLICES) == len(PROPAGATOR_PATHS); got {len(SOURCE_TIMESLICES)} and {len(PROPAGATOR_PATHS)}"
        )
    global_lt = LATTICE_SIZE[3]
    if global_lt % 2 != 0:
        raise ValueError(
            f"Current propagator-entry proton workflow requires an even global Lt for the parity-projector construction; got {global_lt}"
        )
    invalid_timeslices = [t_src for t_src in SOURCE_TIMESLICES if t_src < 0 or t_src >= global_lt]
    if invalid_timeslices:
        raise ValueError(
            f"All source timeslices must satisfy 0 <= t_src < {global_lt}; got {invalid_timeslices}"
        )
    if GAUGE_FIXED is not False:
        raise ValueError(
            f"Current propagator-entry proton workflow is only grounded for GAUGE_FIXED=False; got {GAUGE_FIXED!r}"
        )
    if not RESOURCE_PATH:
        raise ValueError("RESOURCE_PATH must be a non-empty string.")
    if not CLUSTER_LAUNCH:
        raise ValueError("CLUSTER_LAUNCH must be a non-empty string.")
    if not TASK_ARTIFACT.exists() or not PHYSICS_ARTIFACT.exists() or not PLAN_ARTIFACT.exists():
        raise FileNotFoundError(
            "Expected sibling review artifacts next to this script: "
            f"{PHYSICS_ARTIFACT.name}, {TASK_ARTIFACT.name}, and {PLAN_ARTIFACT.name}"
        )


def _load_runtime_modules():
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'numpy'. Activate a PyQUDA Python environment with NumPy installed before running this script."
        ) from exc
    try:
        import cupy as cp
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'cupy'. Activate a PyQUDA environment with CuPy installed before running this script."
        ) from exc
    try:
        from opt_einsum import contract
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'opt_einsum'. Activate a PyQUDA environment with opt_einsum installed before running this script."
        ) from exc
    try:
        from pyquda_utils import core, gamma, io
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda_utils'. If you are running from a local PyQUDA checkout, build/install PyQUDA first "
            "or export PYTHONPATH=~/PyQUDA after following the upstream development instructions."
        ) from exc
    try:
        import pyquda  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda'. The PyQUDA core bindings are not available in this Python environment."
        ) from exc
    return np, cp, contract, core, gamma, io


def _print_handoff_summary() -> None:
    print(f"Workflow ID: {WORKFLOW_ID}")
    print(f"Launch assumption: {CLUSTER_LAUNCH}")
    print(f"Propagator format contract: {PROPAGATOR_FORMAT}")
    print(f"Propagator paths: {PROPAGATOR_PATHS}")
    print(f"Source/sink contract: {SOURCE_TYPE} -> {SINK_TYPE}")
    print(f"Source timeslices: {SOURCE_TIMESLICES}")
    print(f"Correlator output path: {CORRELATOR_OUTPUT}")
    print(f"Gauge-fixed assumption on loaded propagators: {GAUGE_FIXED}")
    print(f"QUDA resource path assumption: {RESOURCE_PATH}")
    print(f"Physics artifact: {PHYSICS_ARTIFACT}")
    print(f"Structured task artifact: {TASK_ARTIFACT}")
    print(f"Implementation plan artifact: {PLAN_ARTIFACT}")
    print("Filesystem contract: propagator inputs must be visible to all ranks; only rank 0 writes output.")
    print("Layout contract: lattice extents must be divisible by the requested QUDA/MPI grid.")


def _load_propagator(path, core, io):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Propagator not found: {path}")
    if PROPAGATOR_FORMAT == "npy" and path.suffix != ".npy":
        raise ValueError(f"Expected an .npy propagator path for PROPAGATOR_FORMAT='npy'; got {path}")
    if PROPAGATOR_FORMAT == "hdf5" and path.suffix not in {".h5", ".hdf5"}:
        raise ValueError(f"Expected an .h5 or .hdf5 propagator path for PROPAGATOR_FORMAT='hdf5'; got {path}")
    if False:
        return io.readNPYPropagator(str(path), 0)
    return io.readNPYPropagator(str(path))


def contract_proton_zero_momentum(propagator, latt_info, t_src, global_lt):
    _, cp, contract, _, gamma, _ = _load_runtime_modules()
    c_matrix = gamma.gamma(2) @ gamma.gamma(8)
    gamma0 = gamma.gamma(0)
    gamma4 = gamma.gamma(8)
    gamma5 = gamma.gamma(15)
    half_t = global_lt // 2
    parity_projector = cp.zeros((global_lt, 4, 4), "<c16")
    parity_projector[:half_t] = (gamma0 + gamma4) / 2
    parity_projector[half_t:] = (gamma0 - gamma4) / 2
    temporal_sign = cp.ones((2 * global_lt,), "<f8")
    temporal_sign[:] = -1
    temporal_sign[half_t : half_t + global_lt] = 1

    projector_local = cp.roll(parity_projector, t_src, 0)[latt_info.gt * latt_info.Lt : (latt_info.gt + 1) * latt_info.Lt]
    sign_local = temporal_sign[global_lt - t_src : 2 * global_lt - t_src][latt_info.gt * latt_info.Lt : (latt_info.gt + 1) * latt_info.Lt]
    proton = cp.zeros((latt_info.Lt,), "<c16")
    proton_data = propagator.data
    for a, b, c in permutations(tuple(range(3))):
        for d, e, f in permutations(tuple(range(3))):
            sign = 1 if b == (a + 1) % 3 else -1
            sign *= 1 if e == (d + 1) % 3 else -1
            proton += (sign * sign_local) * (
                contract(
                    "ij,kl,tmn,wtzyxik,wtzyxjl,wtzyxmn->t",
                    c_matrix @ gamma5,
                    c_matrix @ gamma5,
                    projector_local,
                    proton_data[:, :, :, :, :, :, :, a, d],
                    proton_data[:, :, :, :, :, :, :, b, e],
                    proton_data[:, :, :, :, :, :, :, c, f],
                )
                + contract(
                    "ij,kl,tmn,wtzyxik,wtzyxjn,wtzyxml->t",
                    c_matrix @ gamma5,
                    c_matrix @ gamma5,
                    projector_local,
                    proton_data[:, :, :, :, :, :, :, a, d],
                    proton_data[:, :, :, :, :, :, :, b, e],
                    proton_data[:, :, :, :, :, :, :, c, f],
                )
            )
    return proton


def main() -> None:
    _validate_handoff_contract()
    np, _, _, core, _, io = _load_runtime_modules()
    _print_handoff_summary()
    core.init(GRID_SIZE, LATTICE_SIZE, resource_path=RESOURCE_PATH)
    latt_info = core.LatticeInfo(LATTICE_SIZE, -1, 1.0)
    global_lt = LATTICE_SIZE[3]
    correlators = []
    for propagator_path, t_src in zip(PROPAGATOR_PATHS, SOURCE_TIMESLICES, strict=True):
        propagator = _load_propagator(propagator_path, core, io)
        proton = contract_proton_zero_momentum(propagator, latt_info, t_src, global_lt)
        gathered = core.gatherLattice(proton.real.get(), [1, -1, -1, -1])
        if latt_info.mpi_rank == 0:
            correlators.append(np.roll(gathered, -t_src, 0))
    if latt_info.mpi_rank == 0:
        output = np.asarray(correlators, dtype=np.float64)
        CORRELATOR_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        np.save(CORRELATOR_OUTPUT, output)
        print(f"Saved proton 2pt correlator array to {CORRELATOR_OUTPUT}")
        print("Propagator-entry workflow references:")
        print("- /Users/zhaodianjun/PyQUDA/examples/3_Pion_Proton_2pt.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_io.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/io/__init__.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/core.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/gamma.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/source.py")


if __name__ == "__main__":
    main()
