#!/usr/bin/env python3
"""Complete runnable quark-propagator workflow generated by pyquda-agent."""

from __future__ import annotations

import os
from pathlib import Path
from time import perf_counter

# Fixed workflow: gauge -> stout-smear -> getDirac(multigrid) -> point source at [0,0,0,t_src] -> HDF5 propagator.
# Review the sibling .physics.json, .task.json, and .plan.json artifacts before treating this script as complete.
# HPC handoff contract:
# - launch mode assumption: local
# - gauge input is expected on a filesystem visible to all ranks
# - the target environment must already provide PyQUDA, QUDA, CuPy, and HDF5 support
# - this workflow writes a propagator artifact, not a correlator

WORKFLOW_ID = 'quark_propagator_chroma_point_hdf5_v1'
SCRIPT_PATH = Path(__file__).resolve()
TASK_ARTIFACT = SCRIPT_PATH.with_suffix(".task.json")
PHYSICS_ARTIFACT = SCRIPT_PATH.with_suffix(".physics.json")
PLAN_ARTIFACT = SCRIPT_PATH.with_suffix(".plan.json")
PROBE_ARTIFACT = SCRIPT_PATH.with_suffix(".probe.json")
GAUGE_PATH = Path('/Users/zhaodianjun/PyQUDA/tests/weak_field.lime')
PROPAGATOR_OUTPUT = Path('/Users/zhaodianjun/pyquda-agent/outputs/validate_quark_propagator.h5')
RESOURCE_PATH = '.cache/quda'
CLUSTER_LAUNCH = 'local'
GAUGE_FORMAT = 'chroma_qio'
SOURCE_TYPE = 'point'
SINK_TYPE = 'propagator'
GRID_SIZE = [1, 1, 1, 1]
LATTICE_SIZE = [4, 4, 4, 8]
SOURCE_TIMESLICES = [0]
SOURCE_SPATIAL_ORIGIN = [0, 0, 0]
MASS = -0.277
XI_0 = 1.0
NU = 1.0
COEFF_T = 1.160920226
COEFF_R = 1.160920226
SOLVER_TOL = 1e-12
SOLVER_MAXITER = 1000
MULTIGRID_BLOCKS = [[6, 6, 6, 4], [4, 4, 4, 9]]
STOUT_SMEAR_STEPS = 1
STOUT_SMEAR_RHO = 0.125
STOUT_SMEAR_NDIM = 4


def _nearest_existing_parent(path: Path) -> Path:
    current = path.expanduser().resolve().parent
    while not current.exists() and current != current.parent:
        current = current.parent
    return current


def _validate_output_parent_writable(path: Path, *, label: str) -> None:
    writable_probe = _nearest_existing_parent(path)
    if not writable_probe.exists():
        raise FileNotFoundError(f"Unable to locate an existing parent directory for {label} path {path}")
    if not os.access(writable_probe, os.W_OK):
        raise PermissionError(
            f"{label} path {path} requires a writable parent directory on the submission filesystem; "
            f"nearest existing parent is {writable_probe}"
        )


def _validate_handoff_contract() -> None:
    if GAUGE_FORMAT != "chroma_qio":
        raise ValueError(f"Current quark-propagator workflow requires GAUGE_FORMAT='chroma_qio'; got {GAUGE_FORMAT!r}")
    if SOURCE_TYPE != "point":
        raise ValueError(f"Current quark-propagator workflow requires SOURCE_TYPE='point'; got {SOURCE_TYPE!r}")
    if SINK_TYPE != "propagator":
        raise ValueError(f"Current quark-propagator workflow requires SINK_TYPE='propagator'; got {SINK_TYPE!r}")
    if PROPAGATOR_OUTPUT.suffix not in {".h5", ".hdf5"}:
        raise ValueError(f"Expected an .h5/.hdf5 propagator output path; got {PROPAGATOR_OUTPUT}")
    if len(LATTICE_SIZE) != 4 or len(GRID_SIZE) != 4:
        raise ValueError("LATTICE_SIZE and GRID_SIZE must both contain exactly four integers.")
    if any(value <= 0 for value in LATTICE_SIZE + GRID_SIZE):
        raise ValueError("LATTICE_SIZE and GRID_SIZE must contain strictly positive integers.")
    for axis, (latt_extent, grid_extent) in enumerate(zip(LATTICE_SIZE, GRID_SIZE, strict=True)):
        if latt_extent % grid_extent != 0:
            raise ValueError(
                f"LATTICE_SIZE[{axis}]={latt_extent} must be divisible by GRID_SIZE[{axis}]={grid_extent}"
            )
    if not SOURCE_TIMESLICES:
        raise ValueError("At least one source timeslice is required.")
    if len(SOURCE_TIMESLICES) != 1:
        raise ValueError(f"Current quark-propagator workflow requires exactly one source timeslice; got {SOURCE_TIMESLICES}")
    global_lt = LATTICE_SIZE[3]
    t_src = SOURCE_TIMESLICES[0]
    if t_src < 0 or t_src >= global_lt:
        raise ValueError(f"SOURCE_TIMESLICES[0] must satisfy 0 <= t_src < {global_lt}; got {t_src}")
    if not MULTIGRID_BLOCKS or any(any(item <= 0 for item in block) for block in MULTIGRID_BLOCKS):
        raise ValueError("MULTIGRID_BLOCKS must contain only positive block extents.")
    if STOUT_SMEAR_STEPS is None or STOUT_SMEAR_STEPS <= 0:
        raise ValueError("STOUT_SMEAR_STEPS must be strictly positive.")
    if STOUT_SMEAR_RHO is None or STOUT_SMEAR_RHO <= 0:
        raise ValueError("STOUT_SMEAR_RHO must be strictly positive.")
    if STOUT_SMEAR_NDIM is None or STOUT_SMEAR_NDIM <= 0:
        raise ValueError("STOUT_SMEAR_NDIM must be strictly positive.")
    _validate_output_parent_writable(PROPAGATOR_OUTPUT, label="Propagator output")
    if not TASK_ARTIFACT.exists() or not PHYSICS_ARTIFACT.exists() or not PLAN_ARTIFACT.exists():
        raise FileNotFoundError(
            "Expected sibling review artifacts next to this script: "
            f"{PHYSICS_ARTIFACT.name}, {TASK_ARTIFACT.name}, and {PLAN_ARTIFACT.name}"
        )


def _print_handoff_summary() -> None:
    print(f"Workflow ID: {WORKFLOW_ID}")
    print(f"Launch assumption: {CLUSTER_LAUNCH}")
    print(f"Gauge input path: {GAUGE_PATH}")
    print(f"Propagator output path: {PROPAGATOR_OUTPUT}")
    print(f"Output parent directory: {PROPAGATOR_OUTPUT.expanduser().resolve().parent}")
    print(f"Gauge format contract: {GAUGE_FORMAT}")
    print(f"Source/sink contract: {SOURCE_TYPE} -> {SINK_TYPE}")
    print(f"Point-source spatial origin: {SOURCE_SPATIAL_ORIGIN}")
    print(f"Source timeslices: {SOURCE_TIMESLICES}")
    print(f"QUDA resource path assumption: {RESOURCE_PATH}")
    print(f"Probe artifact path: {PROBE_ARTIFACT}")
    print("Submission precheck: confirm the nearest existing parent of the propagator output path is writable before launch.")
    print("Output contract: save one HDF5 propagator artifact for the requested source timeslice.")
    print("Filesystem contract: gauge input and output directory must be visible on the target launch filesystem.")


def _load_runtime_modules():
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'numpy'. Activate a PyQUDA Python environment with NumPy installed before running this script."
        ) from exc

    try:
        import cupy as cp
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'cupy'. Activate a PyQUDA environment with CuPy installed before running this script."
        ) from exc

    try:
        from pyquda_utils import core, io, source
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda_utils'. If you are running from a local PyQUDA checkout, build/install PyQUDA first "
            "or export PYTHONPATH=~/PyQUDA after following the upstream development instructions."
        ) from exc

    try:
        import pyquda  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda'. The PyQUDA core bindings are not available in this Python environment."
        ) from exc

    return np, cp, core, io, source


def main() -> None:
    _validate_handoff_contract()
    if not GAUGE_PATH.exists():
        raise FileNotFoundError(f"Gauge configuration not found: {GAUGE_PATH}")

    np, cp, core, io, source = _load_runtime_modules()
    _print_handoff_summary()
    core.init(GRID_SIZE, resource_path=RESOURCE_PATH)
    latt_info = core.LatticeInfo(LATTICE_SIZE, -1, XI_0 / NU)
    dirac = core.getDirac(latt_info, MASS, SOLVER_TOL, SOLVER_MAXITER, XI_0, COEFF_T, COEFF_R, MULTIGRID_BLOCKS)

    start = perf_counter()
    gauge = io.readChromaQIOGauge(str(GAUGE_PATH))
    gauge.stoutSmear(STOUT_SMEAR_STEPS, STOUT_SMEAR_RHO, STOUT_SMEAR_NDIM)
    if latt_info.mpi_rank == 0:
        print(f"Loaded and smeared gauge from {GAUGE_PATH} in {perf_counter() - start:.2f} sec")

    propagator = core.LatticePropagator(latt_info)
    t_src = SOURCE_TIMESLICES[0]
    dirac.loadGauge(gauge)
    try:
        solve_start = perf_counter()
        for spin in range(latt_info.Ns):
            for color in range(latt_info.Nc):
                b = source.point(
                    latt_info,
                    [SOURCE_SPATIAL_ORIGIN[0], SOURCE_SPATIAL_ORIGIN[1], SOURCE_SPATIAL_ORIGIN[2], t_src],
                    spin,
                    color,
                )
                x = dirac.invert(b)
                propagator.setFermion(x, spin, color)
        if latt_info.mpi_rank == 0:
            print(f"Completed point-source propagator solve in {perf_counter() - solve_start:.2f} sec")
    finally:
        dirac.freeGauge()

    PROPAGATOR_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    propagator.saveH5(str(PROPAGATOR_OUTPUT), 0)
    if latt_info.mpi_rank == 0:
        print(f"Saved quark propagator to {PROPAGATOR_OUTPUT}")
        print("Workflow references:")
        print("- /Users/zhaodianjun/PyQUDA/examples/2_Quark_Propagator.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_gaussian.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_io.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/io/__init__.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/source.py")


if __name__ == "__main__":
    main()
