#!/usr/bin/env python3
"""Complete runnable rho/vector meson two-point workflow generated by pyquda-agent."""

from __future__ import annotations

import os
from pathlib import Path
from time import perf_counter

# Fixed workflow: gauge -> Clover -> wall source -> local sink -> fixed spatial gamma_i family -> zero momentum -> npy.
# Review the sibling .physics.json, .task.json, and .plan.json artifacts before treating this script as complete.
# HPC handoff contract:
# - launch mode assumption: local
# - gauge input is expected on a filesystem visible to all ranks
# - only rank 0 writes the final correlator artifact
# - this script assumes the target environment already provides PyQUDA, QUDA, CuPy, and MPI layout support

WORKFLOW_ID = 'rho_vector_chroma_wall_local_zero_momentum_npy_v1'
SCRIPT_PATH = Path(__file__).resolve()
TASK_ARTIFACT = SCRIPT_PATH.with_suffix(".task.json")
PHYSICS_ARTIFACT = SCRIPT_PATH.with_suffix(".physics.json")
PLAN_ARTIFACT = SCRIPT_PATH.with_suffix(".plan.json")
PROBE_ARTIFACT = SCRIPT_PATH.with_suffix(".probe.json")
GAUGE_PATH = Path('/Users/zhaodianjun/PyQUDA/tests/weak_field.lime')
CORRELATOR_OUTPUT = Path('/Users/zhaodianjun/pyquda-agent/outputs/validate_rho_vector.npy')
RESOURCE_PATH = '.cache/quda'
CLUSTER_LAUNCH = 'local'
GAUGE_FORMAT = 'chroma_qio'
SOURCE_TYPE = 'wall'
SINK_TYPE = 'local'
GRID_SIZE = [1, 1, 1, 1]
LATTICE_SIZE = [4, 4, 4, 8]
SOURCE_TIMESLICES = [0]
GAMMA_INSERTION_LABELS = ['gamma1_gamma1', 'gamma2_gamma2', 'gamma3_gamma3']
MASS = 0.09253
XI_0 = 4.8965
NU = 0.86679
COEFF_T = 0.8549165664
COEFF_R = 2.32582045
SOLVER_TOL = 1e-12
SOLVER_MAXITER = 1000


def _nearest_existing_parent(path: Path) -> Path:
    current = path.expanduser().resolve().parent
    while not current.exists() and current != current.parent:
        current = current.parent
    return current


def _validate_output_parent_writable(path: Path, *, label: str) -> None:
    writable_probe = _nearest_existing_parent(path)
    if not writable_probe.exists():
        raise FileNotFoundError(f"Unable to locate an existing parent directory for {label} path {path}")
    if not os.access(writable_probe, os.W_OK):
        raise PermissionError(
            f"{label} path {path} requires a writable parent directory on the submission filesystem; "
            f"nearest existing parent is {writable_probe}"
        )


def _validate_handoff_contract() -> None:
    expected_suffixes = {".lime", ".xml"}
    if GAUGE_FORMAT != "chroma_qio":
        raise ValueError(f"Current rho/vector workflow requires GAUGE_FORMAT='chroma_qio'; got {GAUGE_FORMAT!r}")
    if GAUGE_PATH.suffix not in expected_suffixes:
        raise ValueError(
            f"Expected a Chroma/QIO gauge path ending in one of {sorted(expected_suffixes)}; got {GAUGE_PATH}"
        )
    if SOURCE_TYPE != "wall":
        raise ValueError(f"Current rho/vector workflow requires SOURCE_TYPE='wall'; got {SOURCE_TYPE!r}")
    if SINK_TYPE != "local":
        raise ValueError(f"Current rho/vector workflow requires SINK_TYPE='local'; got {SINK_TYPE!r}")
    if CORRELATOR_OUTPUT.suffix != ".npy":
        raise ValueError(f"Expected a .npy correlator output path; got {CORRELATOR_OUTPUT}")
    if len(LATTICE_SIZE) != 4 or len(GRID_SIZE) != 4:
        raise ValueError("LATTICE_SIZE and GRID_SIZE must both contain exactly four integers.")
    if any(value <= 0 for value in LATTICE_SIZE):
        raise ValueError(f"LATTICE_SIZE must be strictly positive; got {LATTICE_SIZE}")
    if any(value <= 0 for value in GRID_SIZE):
        raise ValueError(f"GRID_SIZE must be strictly positive; got {GRID_SIZE}")
    for axis, (latt_extent, grid_extent) in enumerate(zip(LATTICE_SIZE, GRID_SIZE, strict=True)):
        if latt_extent % grid_extent != 0:
            raise ValueError(
                f"LATTICE_SIZE[{axis}]={latt_extent} must be divisible by GRID_SIZE[{axis}]={grid_extent}"
            )
    if not SOURCE_TIMESLICES:
        raise ValueError("At least one source timeslice is required.")
    global_lt = LATTICE_SIZE[3]
    invalid_timeslices = [t_src for t_src in SOURCE_TIMESLICES if t_src < 0 or t_src >= global_lt]
    if invalid_timeslices:
        raise ValueError(
            f"All source timeslices must satisfy 0 <= t_src < {global_lt}; got {invalid_timeslices}"
        )
    if GAMMA_INSERTION_LABELS != ["gamma1_gamma1", "gamma2_gamma2", "gamma3_gamma3"]:
        raise ValueError(
            "Current rho/vector workflow requires GAMMA_INSERTION_LABELS == ['gamma1_gamma1', 'gamma2_gamma2', 'gamma3_gamma3']."
        )
    if not RESOURCE_PATH:
        raise ValueError("RESOURCE_PATH must be a non-empty string.")
    if not CLUSTER_LAUNCH:
        raise ValueError("CLUSTER_LAUNCH must be a non-empty string.")
    _validate_output_parent_writable(CORRELATOR_OUTPUT, label="Correlator output")
    if not TASK_ARTIFACT.exists() or not PHYSICS_ARTIFACT.exists() or not PLAN_ARTIFACT.exists():
        raise FileNotFoundError(
            "Expected sibling review artifacts next to this script: "
            f"{PHYSICS_ARTIFACT.name}, {TASK_ARTIFACT.name}, and {PLAN_ARTIFACT.name}"
        )


def _print_handoff_summary() -> None:
    print(f"Workflow ID: {WORKFLOW_ID}")
    print(f"Launch assumption: {CLUSTER_LAUNCH}")
    print(f"Gauge input path: {GAUGE_PATH}")
    print(f"Correlator output path: {CORRELATOR_OUTPUT}")
    print(f"Output parent directory: {CORRELATOR_OUTPUT.expanduser().resolve().parent}")
    print(f"Gauge format contract: {GAUGE_FORMAT}")
    print(f"Source/sink contract: {SOURCE_TYPE} -> {SINK_TYPE}")
    print(f"Source timeslices: {SOURCE_TIMESLICES}")
    print(f"Fixed gamma insertion family: {GAMMA_INSERTION_LABELS}")
    print(f"QUDA resource path assumption: {RESOURCE_PATH}")
    print(f"Physics artifact: {PHYSICS_ARTIFACT}")
    print(f"Structured task artifact: {TASK_ARTIFACT}")
    print(f"Implementation plan artifact: {PLAN_ARTIFACT}")
    print(f"Probe artifact path: {PROBE_ARTIFACT}")
    print("Filesystem contract: gauge input must be visible to all ranks; only rank 0 writes output.")
    print("Submission assumption: launch under the MPI/GPU layout encoded by GRID_SIZE.")
    print("Submission precheck: confirm the nearest existing parent of the correlator output path is writable before launch.")
    print("Output contract: save a tensor ordered as [source_timeslice, t, gamma_i].")
    print("Dependency contract: numpy, cupy, pyquda_utils, and pyquda must import before heavy work starts.")
    print("Layout contract: lattice extents must be divisible by the requested QUDA/MPI grid.")


def _load_runtime_modules():
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'numpy'. Activate a PyQUDA Python environment with NumPy installed before running this script."
        ) from exc

    try:
        import cupy as cp
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'cupy'. Activate a PyQUDA environment with CuPy installed before running this script."
        ) from exc

    try:
        from pyquda_utils import core, gamma, io
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda_utils'. If you are running from a local PyQUDA checkout, build/install PyQUDA first "
            "or export PYTHONPATH=~/PyQUDA after following the upstream development instructions."
        ) from exc

    try:
        import pyquda  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda'. The PyQUDA core bindings are not available in this Python environment."
        ) from exc

    return np, cp, core, gamma, io


def _gamma_insertion_family(gamma):
    return [
        ("gamma1_gamma1", gamma.gamma(1), gamma.gamma(1)),
        ("gamma2_gamma2", gamma.gamma(2), gamma.gamma(2)),
        ("gamma3_gamma3", gamma.gamma(4), gamma.gamma(4)),
    ]


def main() -> None:
    _validate_handoff_contract()
    if not GAUGE_PATH.exists():
        raise FileNotFoundError(f"Gauge configuration not found: {GAUGE_PATH}")

    np, cp, core, gamma, io = _load_runtime_modules()
    _print_handoff_summary()
    core.init(GRID_SIZE, LATTICE_SIZE, resource_path=RESOURCE_PATH)
    latt_info = core.LatticeInfo(LATTICE_SIZE, -1, XI_0 / NU)
    dirac = core.getClover(latt_info, MASS, SOLVER_TOL, SOLVER_MAXITER, XI_0, COEFF_T, COEFF_R)
    gamma5 = gamma.gamma(15)
    vol = latt_info.volume
    ns = 4
    nc = 3
    insertion_family = _gamma_insertion_family(gamma)
    rho = np.zeros((len(SOURCE_TIMESLICES), LATTICE_SIZE[3], len(insertion_family)), "<c16")

    start = perf_counter()
    gauge = io.readQIOGauge(str(GAUGE_PATH))
    if latt_info.mpi_rank == 0:
        print(f"Loaded gauge from {GAUGE_PATH} in {perf_counter() - start:.2f} sec")

    with dirac.useGauge(gauge):
        for t_idx, t_src in enumerate(SOURCE_TIMESLICES):
            invert_start = perf_counter()
            propagator = core.invert(dirac, "wall", t_src)
            if latt_info.mpi_rank == 0:
                print(f"Inversion for wall source at t={t_src} took {perf_counter() - invert_start:.2f} sec")

            reshaped = propagator.data.reshape(vol, ns, ns, nc, nc)
            for gamma_idx, (label, gamma_src, gamma_snk) in enumerate(insertion_family):
                tmp = cp.einsum(
                    "ij,xkjba,kl,xliba->x",
                    gamma_src @ gamma5,
                    reshaped.conj(),
                    gamma5 @ gamma_snk,
                    reshaped,
                    optimize=True,
                )
                correlator = cp.einsum(
                    "wtzyx->t",
                    tmp.reshape(2, latt_info.Lt, latt_info.Lz, latt_info.Ly, latt_info.Lx // 2),
                    optimize=True,
                )
                correlator = cp.roll(correlator, -t_src)
                gathered = core.gatherLattice(correlator.get(), [0, -1, -1, -1])
                if latt_info.mpi_rank == 0:
                    rho[t_idx, :, gamma_idx] = gathered

    if latt_info.mpi_rank == 0:
        CORRELATOR_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        np.save(CORRELATOR_OUTPUT, rho)
        print(f"Saved rho/vector correlator tensor to {CORRELATOR_OUTPUT}")
        print("Gamma-axis order: ['gamma1_gamma1', 'gamma2_gamma2', 'gamma3_gamma3']")
        print("Workflow references:")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_mesonspec.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_mesonspec.ini.xml")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_io.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/io/__init__.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/core.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/gamma.py")


if __name__ == "__main__":
    main()
