#!/usr/bin/env python3
"""Complete runnable pion two-point workflow from existing propagators generated by pyquda-agent."""

from __future__ import annotations

import os
from pathlib import Path

# Fixed workflow: existing propagator(s) -> local gamma5 contraction -> zero momentum -> npy.
# Review the sibling .physics.json, .task.json, and .plan.json artifacts before treating this script as complete.
# HPC handoff contract:
# - launch mode assumption: local
# - propagator inputs are expected on a filesystem visible to all ranks
# - the loaded propagators must already match the stated lattice/grid metadata and gauge-fixing assumption
# - only rank 0 writes the final correlator artifact
# - this script assumes the target environment already provides PyQUDA, QUDA, CuPy, and MPI layout support

WORKFLOW_ID = 'pion_2pt_existing_propagator_local_zero_momentum_npy_v1'
SCRIPT_PATH = Path(__file__).resolve()
TASK_ARTIFACT = SCRIPT_PATH.with_suffix(".task.json")
PHYSICS_ARTIFACT = SCRIPT_PATH.with_suffix(".physics.json")
PLAN_ARTIFACT = SCRIPT_PATH.with_suffix(".plan.json")
PROBE_ARTIFACT = SCRIPT_PATH.with_suffix(".probe.json")
PROPAGATOR_PATHS = ['/tmp/pion_prop_0.npy']
PROPAGATOR_FORMAT = 'npy'
SOURCE_TYPE = 'wall'
CORRELATOR_OUTPUT = Path('/Users/zhaodianjun/pyquda-agent/outputs/validate_pion_2pt_existing_propagator.npy')
RESOURCE_PATH = '.cache/quda'
CLUSTER_LAUNCH = 'local'
GRID_SIZE = [1, 1, 1, 1]
LATTICE_SIZE = [4, 4, 4, 8]
GAUGE_FIXED = True


def _resolved_propagator_paths():
    return [Path(path).expanduser().resolve() for path in PROPAGATOR_PATHS]


def _nearest_existing_parent(path: Path) -> Path:
    current = path.expanduser().resolve().parent
    while not current.exists() and current != current.parent:
        current = current.parent
    return current


def _validate_output_parent_writable(path: Path, *, label: str) -> None:
    writable_probe = _nearest_existing_parent(path)
    if not writable_probe.exists():
        raise FileNotFoundError(f"Unable to locate an existing parent directory for {label} path {path}")
    if not os.access(writable_probe, os.W_OK):
        raise PermissionError(
            f"{label} path {path} requires a writable parent directory on the submission filesystem; "
            f"nearest existing parent is {writable_probe}"
        )


def _propagator_input_dirs():
    return sorted({str(path.parent) for path in _resolved_propagator_paths()})


def _propagator_manifest():
    return [
        {"index": index, "path": str(path)}
        for index, path in enumerate(_resolved_propagator_paths())
    ]


def _validate_handoff_contract() -> None:
    if not PROPAGATOR_PATHS:
        raise ValueError("At least one propagator path is required.")
    resolved_paths = _resolved_propagator_paths()
    if len({str(path) for path in resolved_paths}) != len(resolved_paths):
        raise ValueError("Duplicate propagator paths are not allowed in the input manifest.")
    if SOURCE_TYPE not in {"wall", "point"}:
        raise ValueError(f"Current propagator-entry family requires SOURCE_TYPE in {'wall', 'point'}; got {SOURCE_TYPE!r}")
    if CORRELATOR_OUTPUT.suffix != ".npy":
        raise ValueError(f"Expected a .npy correlator output path; got {CORRELATOR_OUTPUT}")
    if any(path == CORRELATOR_OUTPUT.expanduser().resolve() for path in resolved_paths):
        raise ValueError("CORRELATOR_OUTPUT must not reuse a propagator input path.")
    if len(LATTICE_SIZE) != 4 or len(GRID_SIZE) != 4:
        raise ValueError("LATTICE_SIZE and GRID_SIZE must both contain exactly four integers.")
    if any(value <= 0 for value in LATTICE_SIZE):
        raise ValueError(f"LATTICE_SIZE must be strictly positive; got {LATTICE_SIZE}")
    if any(value <= 0 for value in GRID_SIZE):
        raise ValueError(f"GRID_SIZE must be strictly positive; got {GRID_SIZE}")
    for axis, (latt_extent, grid_extent) in enumerate(zip(LATTICE_SIZE, GRID_SIZE, strict=True)):
        if latt_extent % grid_extent != 0:
            raise ValueError(
                f"LATTICE_SIZE[{axis}]={latt_extent} must be divisible by GRID_SIZE[{axis}]={grid_extent}"
            )
    if PROPAGATOR_FORMAT not in {"npy", "hdf5", "chroma_qio"}:
        raise ValueError(
            f"Expected PROPAGATOR_FORMAT in {'npy', 'hdf5', 'chroma_qio'} for the grounded propagator-entry family; got {PROPAGATOR_FORMAT!r}"
        )
    if not RESOURCE_PATH:
        raise ValueError("RESOURCE_PATH must be a non-empty string.")
    if not CLUSTER_LAUNCH:
        raise ValueError("CLUSTER_LAUNCH must be a non-empty string.")
    _validate_output_parent_writable(CORRELATOR_OUTPUT, label="Correlator output")
    if not TASK_ARTIFACT.exists() or not PHYSICS_ARTIFACT.exists() or not PLAN_ARTIFACT.exists():
        raise FileNotFoundError(
            "Expected sibling review artifacts next to this script: "
            f"{PHYSICS_ARTIFACT.name}, {TASK_ARTIFACT.name}, and {PLAN_ARTIFACT.name}"
        )


def _load_runtime_modules():
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'numpy'. Activate a PyQUDA Python environment with NumPy installed before running this script."
        ) from exc
    try:
        import cupy as cp
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'cupy'. Activate a PyQUDA environment with CuPy installed before running this script."
        ) from exc
    try:
        from pyquda_utils import core, gamma, io
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda_utils'. If you are running from a local PyQUDA checkout, build/install PyQUDA first "
            "or export PYTHONPATH=~/PyQUDA after following the upstream development instructions."
        ) from exc
    try:
        import pyquda  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda'. The PyQUDA core bindings are not available in this Python environment."
        ) from exc
    return np, cp, core, gamma, io


def _print_handoff_summary() -> None:
    print(f"Workflow ID: {WORKFLOW_ID}")
    print(f"Launch assumption: {CLUSTER_LAUNCH}")
    print(f"Propagator format: {PROPAGATOR_FORMAT}")
    print(f"Stored source convention: {SOURCE_TYPE}")
    print(f"Propagator input count: {len(PROPAGATOR_PATHS)}")
    print(f"Input directories: {_propagator_input_dirs()}")
    print(f"Input manifest: {_propagator_manifest()}")
    print(f"Correlator output path: {CORRELATOR_OUTPUT}")
    print(f"Output parent directory: {CORRELATOR_OUTPUT.expanduser().resolve().parent}")
    print(f"Lattice/grid contract: {LATTICE_SIZE} over grid {GRID_SIZE}")
    print(f"QUDA resource path assumption: {RESOURCE_PATH}")
    print(f"Physics artifact: {PHYSICS_ARTIFACT}")
    print(f"Structured task artifact: {TASK_ARTIFACT}")
    print(f"Implementation plan artifact: {PLAN_ARTIFACT}")
    print(f"Gauge-fixed assumption on loaded propagators: {GAUGE_FIXED}")
    print(f"Probe artifact path: {PROBE_ARTIFACT}")
    print("Filesystem contract: propagator inputs must be visible to all ranks; only rank 0 writes output.")
    print("Input mutability contract: propagator inputs are treated as immutable handoff artifacts and are never overwritten.")
    print("Directory convention: prefer a dedicated writable results directory instead of writing beside stored propagator handoff artifacts.")
    print("Submission assumption: launch under the MPI/GPU layout encoded by GRID_SIZE.")
    print("Submission precheck: confirm the nearest existing parent of the correlator output path is writable before launch.")
    print("Output contract: ensure the correlator output parent is writable by the rank that saves the final artifact.")
    print("Dependency contract: numpy, cupy, pyquda_utils, and pyquda must import before heavy work starts.")
    print("Layout contract: lattice extents must be divisible by the requested QUDA/MPI grid.")


def _load_propagator(path, core, io):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Propagator not found: {path}")
    if PROPAGATOR_FORMAT == "npy" and path.suffix != ".npy":
        raise ValueError(f"Expected an .npy propagator path for PROPAGATOR_FORMAT='npy'; got {path}")
    if PROPAGATOR_FORMAT == "hdf5" and path.suffix not in {".h5", ".hdf5"}:
        raise ValueError(f"Expected an .h5 or .hdf5 propagator path for PROPAGATOR_FORMAT='hdf5'; got {path}")
    if False:
        return io.readNPYPropagator(str(path), 0)
    return io.readNPYPropagator(str(path))


def contract_pion_zero_momentum(propagator, latt_info):
    _, cp, _, gamma, _ = _load_runtime_modules()
    gamma5 = gamma.gamma(15)
    vol = latt_info.volume
    nc = 3
    ns = 4
    tmp = cp.einsum(
        "ij,xkjba,kl,xliba->x",
        gamma5 @ gamma5,
        propagator.data.reshape(vol, ns, ns, nc, nc).conj(),
        gamma5 @ gamma5,
        propagator.data.reshape(vol, ns, ns, nc, nc),
        optimize=True,
    )
    return cp.einsum(
        "wtzyx->t",
        tmp.reshape(2, latt_info.Lt, latt_info.Lz, latt_info.Ly, latt_info.Lx // 2),
        optimize=True,
    )


def main() -> None:
    _validate_handoff_contract()
    np, _, core, _, io = _load_runtime_modules()
    _print_handoff_summary()
    latt_info = core.LatticeInfo(LATTICE_SIZE, -1, 1.0)
    correlators = []
    for propagator_path in PROPAGATOR_PATHS:
        propagator = _load_propagator(propagator_path, core, io)
        corr = contract_pion_zero_momentum(propagator, latt_info)
        gathered = core.gatherLattice(corr.real.get(), [0, -1, -1, -1])
        if latt_info.mpi_rank == 0:
            correlators.append(gathered)
    if latt_info.mpi_rank == 0:
        output = np.asarray(correlators, dtype=np.float64)
        CORRELATOR_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        np.save(CORRELATOR_OUTPUT, output)
        print(f"Saved pion 2pt correlator array to {CORRELATOR_OUTPUT}")
        print("Propagator-entry workflow references:")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_mesonspec.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_io.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/io/__init__.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/core.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/gamma.py")
        print("- /Users/zhaodianjun/PyQUDA/examples/3_Pion_Proton_2pt.py")


if __name__ == "__main__":
    main()
