#!/usr/bin/env python3
"""Complete runnable pion-dispersion workflow generated by pyquda-agent."""

from __future__ import annotations

import os
from pathlib import Path
from time import perf_counter

# Fixed workflow: gauge -> Clover inversion -> point source at [0, 0, 0, t_src] -> fixed momentum list -> npy.
# Review the sibling .physics.json, .task.json, and .plan.json artifacts before treating this script as complete.
# HPC handoff contract:
# - launch mode assumption: local
# - gauge input is expected on a filesystem visible to all ranks
# - only rank 0 writes the final correlator artifact
# - this script assumes the target environment already provides PyQUDA, QUDA, CuPy, opt_einsum, and MPI layout support

WORKFLOW_ID = 'pion_dispersion_chroma_point_momentum_npy_v1'
SCRIPT_PATH = Path(__file__).resolve()
TASK_ARTIFACT = SCRIPT_PATH.with_suffix(".task.json")
PHYSICS_ARTIFACT = SCRIPT_PATH.with_suffix(".physics.json")
PLAN_ARTIFACT = SCRIPT_PATH.with_suffix(".plan.json")
PROBE_ARTIFACT = SCRIPT_PATH.with_suffix(".probe.json")
GAUGE_PATH = Path('/Users/zhaodianjun/PyQUDA/tests/weak_field.lime')
CORRELATOR_OUTPUT = Path('/Users/zhaodianjun/pyquda-agent/outputs/validate_pion_dispersion.npy')
RESOURCE_PATH = '.cache/quda'
CLUSTER_LAUNCH = 'local'
GAUGE_FORMAT = 'chroma_qio'
SOURCE_TYPE = 'point'
SINK_TYPE = 'local'
GRID_SIZE = [1, 1, 1, 1]
LATTICE_SIZE = [4, 4, 4, 8]
SOURCE_TIMESLICES = [0]
SOURCE_SPATIAL_ORIGIN = [0, 0, 0]
MOMENTUM_LIST = [[0, 0, 0], [0, 0, 1], [0, 1, 1], [1, 1, 1], [0, 0, 2], [0, 1, 2], [1, 1, 2], [0, 2, 2], [1, 2, 2]]
MASS = 0.09253
XI_0 = 4.8965
NU = 0.86679
COEFF_T = 0.8549165664
COEFF_R = 2.32582045
SOLVER_TOL = 1e-12
SOLVER_MAXITER = 1000


def _nearest_existing_parent(path: Path) -> Path:
    current = path.expanduser().resolve().parent
    while not current.exists() and current != current.parent:
        current = current.parent
    return current


def _validate_output_parent_writable(path: Path, *, label: str) -> None:
    writable_probe = _nearest_existing_parent(path)
    if not writable_probe.exists():
        raise FileNotFoundError(f"Unable to locate an existing parent directory for {label} path {path}")
    if not os.access(writable_probe, os.W_OK):
        raise PermissionError(
            f"{label} path {path} requires a writable parent directory on the submission filesystem; "
            f"nearest existing parent is {writable_probe}"
        )


def _validate_handoff_contract() -> None:
    expected_suffixes = {".lime", ".xml"}
    if GAUGE_FORMAT != "chroma_qio":
        raise ValueError(f"Current pion-dispersion workflow requires GAUGE_FORMAT='chroma_qio'; got {GAUGE_FORMAT!r}")
    if GAUGE_PATH.suffix not in expected_suffixes:
        raise ValueError(
            f"Expected a Chroma/QIO gauge path ending in one of {sorted(expected_suffixes)}; got {GAUGE_PATH}"
        )
    if SOURCE_TYPE != "point":
        raise ValueError(f"Current pion-dispersion workflow requires SOURCE_TYPE='point'; got {SOURCE_TYPE!r}")
    if SINK_TYPE != "local":
        raise ValueError(f"Current pion-dispersion workflow requires SINK_TYPE='local'; got {SINK_TYPE!r}")
    if CORRELATOR_OUTPUT.suffix != ".npy":
        raise ValueError(f"Expected a .npy correlator output path; got {CORRELATOR_OUTPUT}")
    if len(LATTICE_SIZE) != 4 or len(GRID_SIZE) != 4:
        raise ValueError("LATTICE_SIZE and GRID_SIZE must both contain exactly four integers.")
    if any(value <= 0 for value in LATTICE_SIZE):
        raise ValueError(f"LATTICE_SIZE must be strictly positive; got {LATTICE_SIZE}")
    if any(value <= 0 for value in GRID_SIZE):
        raise ValueError(f"GRID_SIZE must be strictly positive; got {GRID_SIZE}")
    for axis, (latt_extent, grid_extent) in enumerate(zip(LATTICE_SIZE, GRID_SIZE, strict=True)):
        if latt_extent % grid_extent != 0:
            raise ValueError(
                f"LATTICE_SIZE[{axis}]={latt_extent} must be divisible by GRID_SIZE[{axis}]={grid_extent}"
            )
    if not SOURCE_TIMESLICES:
        raise ValueError("At least one source timeslice is required.")
    global_lt = LATTICE_SIZE[3]
    invalid_timeslices = [t_src for t_src in SOURCE_TIMESLICES if t_src < 0 or t_src >= global_lt]
    if invalid_timeslices:
        raise ValueError(
            f"All source timeslices must satisfy 0 <= t_src < {global_lt}; got {invalid_timeslices}"
        )
    if len(SOURCE_SPATIAL_ORIGIN) != 3:
        raise ValueError("SOURCE_SPATIAL_ORIGIN must contain exactly three integers.")
    if not MOMENTUM_LIST:
        raise ValueError("MOMENTUM_LIST must be non-empty.")
    if any(len(mom) != 3 for mom in MOMENTUM_LIST):
        raise ValueError(f"Each momentum vector must contain exactly three integers; got {MOMENTUM_LIST}")
    if any(any(not isinstance(component, int) for component in mom) for mom in MOMENTUM_LIST):
        raise ValueError(f"Each momentum component must be an integer; got {MOMENTUM_LIST}")
    if not RESOURCE_PATH:
        raise ValueError("RESOURCE_PATH must be a non-empty string.")
    if not CLUSTER_LAUNCH:
        raise ValueError("CLUSTER_LAUNCH must be a non-empty string.")
    _validate_output_parent_writable(CORRELATOR_OUTPUT, label="Correlator output")
    if not TASK_ARTIFACT.exists() or not PHYSICS_ARTIFACT.exists() or not PLAN_ARTIFACT.exists():
        raise FileNotFoundError(
            "Expected sibling review artifacts next to this script: "
            f"{PHYSICS_ARTIFACT.name}, {TASK_ARTIFACT.name}, and {PLAN_ARTIFACT.name}"
        )


def _print_handoff_summary() -> None:
    print(f"Workflow ID: {WORKFLOW_ID}")
    print(f"Launch assumption: {CLUSTER_LAUNCH}")
    print(f"Gauge input path: {GAUGE_PATH}")
    print(f"Correlator output path: {CORRELATOR_OUTPUT}")
    print(f"Output parent directory: {CORRELATOR_OUTPUT.expanduser().resolve().parent}")
    print(f"Gauge format contract: {GAUGE_FORMAT}")
    print(f"Source/sink contract: {SOURCE_TYPE} -> {SINK_TYPE}")
    print(f"Source timeslices: {SOURCE_TIMESLICES}")
    print(f"Source spatial origin: {SOURCE_SPATIAL_ORIGIN}")
    print(f"Momentum list: {MOMENTUM_LIST}")
    print(f"QUDA resource path assumption: {RESOURCE_PATH}")
    print(f"Physics artifact: {PHYSICS_ARTIFACT}")
    print(f"Structured task artifact: {TASK_ARTIFACT}")
    print(f"Implementation plan artifact: {PLAN_ARTIFACT}")
    print(f"Probe artifact path: {PROBE_ARTIFACT}")
    print("Filesystem contract: gauge input must be visible to all ranks; only rank 0 writes output.")
    print("Submission assumption: launch under the MPI/GPU layout encoded by GRID_SIZE.")
    print("Submission precheck: confirm the nearest existing parent of the correlator output path is writable before launch.")
    print("Output contract: ensure the correlator output parent is writable by the rank that saves the final artifact.")
    print("Dependency contract: numpy, cupy, pyquda_utils, and pyquda must import before heavy work starts.")
    print("Layout contract: lattice extents must be divisible by the requested QUDA/MPI grid.")


def _load_runtime_modules():
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'numpy'. Activate a PyQUDA Python environment with NumPy installed before running this script."
        ) from exc

    try:
        import cupy as cp
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'cupy'. Activate a PyQUDA environment with CuPy installed before running this script."
        ) from exc

    try:
        from opt_einsum import contract
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing runtime dependency 'opt_einsum'. Activate a PyQUDA environment with opt_einsum installed before running this script."
        ) from exc

    try:
        from pyquda_utils import core, gamma, io, phase
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda_utils'. If you are running from a local PyQUDA checkout, build/install PyQUDA first "
            "or export PYTHONPATH=~/PyQUDA after following the upstream development instructions."
        ) from exc

    try:
        import pyquda  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Unable to import 'pyquda'. The PyQUDA core bindings are not available in this Python environment."
        ) from exc

    return np, cp, contract, core, gamma, io, phase


def main() -> None:
    _validate_handoff_contract()
    if not GAUGE_PATH.exists():
        raise FileNotFoundError(f"Gauge configuration not found: {GAUGE_PATH}")

    np, cp, contract, core, gamma, io, phase = _load_runtime_modules()
    _print_handoff_summary()
    core.init(GRID_SIZE, LATTICE_SIZE, resource_path=RESOURCE_PATH)
    latt_info = core.LatticeInfo(LATTICE_SIZE, -1, XI_0 / NU)
    dirac = core.getClover(latt_info, MASS, SOLVER_TOL, SOLVER_MAXITER, XI_0, COEFF_T, COEFF_R)
    gamma5 = gamma.gamma(15)
    momentum_phase = phase.MomentumPhase(latt_info).getPhases(MOMENTUM_LIST)

    start = perf_counter()
    gauge = io.readQIOGauge(str(GAUGE_PATH))
    if latt_info.mpi_rank == 0:
        print(f"Loaded gauge from {GAUGE_PATH} in {perf_counter() - start:.2f} sec")

    pion = cp.zeros((len(SOURCE_TIMESLICES), len(MOMENTUM_LIST), latt_info.Lt), "<c16")

    with dirac.useGauge(gauge):
        for t_idx, t_src in enumerate(SOURCE_TIMESLICES):
            invert_start = perf_counter()
            propagator = core.invert(dirac, "point", [SOURCE_SPATIAL_ORIGIN[0], SOURCE_SPATIAL_ORIGIN[1], SOURCE_SPATIAL_ORIGIN[2], t_src])
            if latt_info.mpi_rank == 0:
                print(f"Inversion for point source at x=y=z=0, t={t_src} took {perf_counter() - invert_start:.2f} sec")

            pion[t_idx] += contract(
                "pwtzyx,wtzyxjiba,jk,wtzyxklba,li->pt",
                momentum_phase,
                propagator.data.conj(),
                gamma5 @ gamma5,
                propagator.data,
                gamma5 @ gamma5,
            )

    gathered = core.gatherLattice(pion.real.get(), [2, -1, -1, -1])
    if latt_info.mpi_rank == 0:
        for t_idx, t_src in enumerate(SOURCE_TIMESLICES):
            gathered[t_idx] = np.roll(gathered[t_idx], -t_src, 1)
        twopt = gathered.mean(0)
        CORRELATOR_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        np.save(CORRELATOR_OUTPUT, twopt)
        print(f"Saved pion dispersion correlator array to {CORRELATOR_OUTPUT}")
        print("Workflow references:")
        print("- /Users/zhaodianjun/PyQUDA/examples/5_Pion_Dispersion.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_mesonspec.py")
        print("- /Users/zhaodianjun/PyQUDA/tests/test_io.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/io/__init__.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/source.py")
        print("- /Users/zhaodianjun/PyQUDA/pyquda_utils/core.py")


if __name__ == "__main__":
    main()
